# Problem 1

## Part 1.Explain the importance of interpretability when training machine learning models. Why is model explainability necessary?

The importance of interpretability of ML model is to let every user who don't know ML easlier to understand how the model makes decisions thus they will trust the model better. It also help us to debug and identify the errors in the model to better refine the model. In this case, it can help decision-makers act confidently. Also regulations require models to explain their outputs as well. A lack of explainability can lead to legal consequences if decisions cannot be justified.

## Part 2. Perform feature selection for the Diabetes regression dataset using FeatureSelector(). How many features are discarded?

In [ ]:
pip install autofeat

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 302.0/302.0 kB 21.7 MB/s eta 0:00:00


In [ ]:
from sklearn.datasets import load_diabetes
import pandas as pd
from autofeat import FeatureSelector

In [ ]:
diabetes = load_diabetes()
X = pd.DataFrame(diabetes.data, columns=diabetes.feature_names)
y = diabetes.target

feature_selector = FeatureSelector()
X_selected = feature_selector.fit_transform(X, y)
num_original_features = X.shape[1]
num_selected_features = X_selected.shape[1]
features_discarded = num_original_features - num_selected_features

print(f"Original features: {num_original_features}")
print(f"Selected features: {num_selected_features}")
print(f"Features discarded: {features_discarded}")

Original features: 10
Selected features: 6
Features discarded: 4


/usr/local/lib/python3.10/dist-packages/autofeat/featsel.py:270: FutureWarning: Series.ravel is deprecated. The underlying array is already 1D, so ravel is not necessary.  Use `to_numpy()` for conversion to a numpy array instead.
  if np.max(np.abs(correlations[c].ravel()[:i])) < 0.9:


## Part 3. Perform a train-test split on your dataset. Select a regression model from skLearn and fit it to the training dataset. What is the R2 score on the training and test set?

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X_selected, y, test_size=0.2, random_state=42)

model = LinearRegression()
model.fit(X_train, y_train)

y_train_pred = model.predict(X_train)
y_test_pred = model.predict(X_test)

r2_score_train = r2_score(y_train, y_train_pred)
r2_score_test = r2_score(y_test, y_test_pred)

print(f"R2 score on training set: {r2_score_train}")
print(f"R2 score on test set: {r2_score_test}")

R2 score on training set: 0.5212927960835636
R2 score on test set: 0.46323772750271597


## Part 4. Keepingthetrainandtestdatasetthesame,run3featureengineeringstepsusingAutoFeatRegressor(). What is the R2 score on the training and test set now? Mention any five new features generated by the output of AutoFeatRegressor().

In [ ]:
from autofeat import AutoFeatRegressor

auto_feat = AutoFeatRegressor(verbose=1, feateng_steps=3)

X_train_auto = auto_feat.fit_transform(X_train, y_train)

X_test_auto = auto_feat.transform(X_test)


[featsel] Scaling data...done.


/usr/local/lib/python3.10/dist-packages/autofeat/featsel.py:270: FutureWarning: Series.ravel is deprecated. The underlying array is already 1D, so ravel is not necessary.  Use `to_numpy()` for conversion to a numpy array instead.
  if np.max(np.abs(correlations[c].ravel()[:i])) < 0.9:


In [ ]:

model_auto = LinearRegression()
model_auto.fit(X_train_auto, y_train)

y_train_pred_auto = model_auto.predict(X_train_auto)
y_test_pred_auto = model_auto.predict(X_test_auto)

r2_train_auto = r2_score(y_train, y_train_pred_auto)
r2_test_auto = r2_score(y_test, y_test_pred_auto)

print(f"R^2 score on training set with AutoFeat: {r2_train_auto:.4f}")
print(f"R^2 score on test set with AutoFeat: {r2_test_auto:.4f}")


R^2 score on training set with AutoFeat: 0.6013
R^2 score on test set with AutoFeat: 0.4603


In [ ]:
# Get the names of the generated features
new_features = set(X_train_auto.columns) - set(X_train.columns)
print(f"New features generated by AutoFeat: {list(new_features)[:5]}")


New features generated by AutoFeat: ['s3/Abs(bmi)', '1/(1/bp + 1/bmi)', '1/(bmi - s1**2)', 'exp(bmi)*exp(bp)', 'exp(s1**3/bp)']


# Problem 2.


## Part1.

In [ ]:
!pip install -U "ray[tune]"

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 101.7/101.7 kB 8.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 66.8/66.8 MB 29.7 MB/s eta 0:00:00


In [ ]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.datasets import mnist

import ray
from ray import tune
from ray.train.tensorflow.keras import ReportCheckpointCallback

from ray.train.tensorflow.keras import ReportCheckpointCallback

In [ ]:
from ray import tune
from ray.train.tensorflow.keras import ReportCheckpointCallback
import tensorflow as tf
from ray.air import session

def train_mnist(config):
    batch_size = config["batch_size"]
    epochs = 12

    (x_train, y_train), (x_test, y_test) = tf.keras.datasets.mnist.load_data()
    x_train, x_test = x_train / 255.0, x_test / 255.0

    model = tf.keras.models.Sequential([
        tf.keras.layers.Input(shape=(28, 28, 1)),
        tf.keras.layers.Conv2D(filters=config["conv_filters"], kernel_size=(5, 5), activation="relu"),
        tf.keras.layers.MaxPooling2D(pool_size=(2, 2)),
        tf.keras.layers.Conv2D(filters=2 * config["conv_filters"], kernel_size=(5, 5), activation="relu"),
        tf.keras.layers.MaxPooling2D(pool_size=(2, 2)),
        tf.keras.layers.Flatten(),
        tf.keras.layers.Dense(120, activation="relu"),
        tf.keras.layers.Dense(84, activation="relu"),
        tf.keras.layers.Dropout(config["dropout"]),
        tf.keras.layers.Dense(10, activation="softmax"),
    ])

    model.compile(
        optimizer=tf.keras.optimizers.Adam(learning_rate=config["lr"]),
        loss="sparse_categorical_crossentropy",
        metrics=["accuracy"]
    )

    history = model.fit(
        x_train, y_train,
        batch_size=batch_size,
        epochs=epochs,
        validation_data=(x_test, y_test),
        verbose=0
    )

    # Report metrics
    session.report({
        "mean_accuracy": history.history["accuracy"][-1],
        # "val_accuracy": history.history["val_accuracy"][-1]
    })


In [ ]:
import ray

# 清理之前的 Ray 实例
ray.shutdown()

# 重新初始化
ray.init()
print(ray.cluster_resources())


2024-12-05 15:02:21,625	INFO worker.py:1821 -- Started a local Ray instance.


{'accelerator_type:A100': 1.0, 'node:__internal_head__': 1.0, 'CPU': 12.0, 'memory': 53632175310.0, 'node:172.28.0.12': 1.0, 'object_store_memory': 26816087654.0, 'GPU': 1.0}


In [ ]:
ray.init(ignore_reinit_error=True)
print(ray.cluster_resources())

2024-12-05 15:02:22,753	INFO worker.py:1654 -- Calling ray.init() again after it has already been called.


{'accelerator_type:A100': 1.0, 'node:__internal_head__': 1.0, 'CPU': 12.0, 'object_store_memory': 26816087654.0, 'node:172.28.0.12': 1.0, 'memory': 53632175310.0, 'GPU': 1.0}


In [ ]:
import ray
ray.shutdown()  # 清理之前的 Ray 状态
ray.init()

2024-12-05 15:02:26,568	INFO worker.py:1821 -- Started a local Ray instance.


RayContext(dashboard_url='', python_version='3.10.12', ray_version='2.40.0', ray_commit='22541c38dbef25286cd6d19f1c151bf4fd62f2ed')

## Part 2.

#### Grid Search

In [ ]:
import time
start_time = time.time()
analysis = tune.run(
    train_mnist,
    resources_per_trial={"cpu": 1, "gpu": 0.5},
    config={
        "conv_filters": tune.grid_search([64, 128, 256]),
        "lr": tune.grid_search([0.001, 0.01, 0.1]),
        "dropout": tune.uniform(0, 1),
        "batch_size": tune.grid_search([64, 128, 256]),
    },
    metric="mean_accuracy",
    mode="max"
)
end_time = time.time()


+--------------------------------------------------------------------+
| Configuration for experiment     train_mnist_2024-12-05_14-26-51   |
+--------------------------------------------------------------------+
| Search algorithm                 BasicVariantGenerator             |
| Scheduler                        FIFOScheduler                     |
| Number of trials                 27                                |
+--------------------------------------------------------------------+

View detailed results here: /root/ray_results/train_mnist_2024-12-05_14-26-51
To visualize your results with TensorBoard, run: `tensorboard --logdir /tmp/ray/session_2024-12-05_14-26-48_632070_1199/artifacts/2024-12-05_14-26-51/train_mnist_2024-12-05_14-26-51/driver_artifacts`

Trial status: 27 PENDING
Current time: 2024-12-05 14:26:55. Total running time: 0s
Logical resource usage: 2.0/12 CPUs, 1.0/1 GPUs (0.0/1.0 accelerator_type:L4)
+-------------------------------------------------------------

(pid=3421) 2024-12-05 14:26:56.834145: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:485] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
(pid=3421) 2024-12-05 14:26:56.856656: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:8454] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
(pid=3421) 2024-12-05 14:26:56.863182: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1452] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
(pid=3421) 2024-12-05 14:26:58.091632: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT



Trial train_mnist_f80bd_00000 started with configuration:
+--------------------------------------------------+
| Trial train_mnist_f80bd_00000 config             |
+--------------------------------------------------+
| batch_size                                    64 |
| conv_filters                                  64 |
| dropout                                  0.08001 |
| lr                                         0.001 |
+--------------------------------------------------+

(train_mnist pid=3421) Downloading data from https://storage.googleapis.com/tensorflow/tf-keras-datasets/mnist.npz
Trial train_mnist_f80bd_00001 started with configuration:
+--------------------------------------------------+
| Trial train_mnist_f80bd_00001 config             |
+--------------------------------------------------+
| batch_size                                   128 |
| conv_filters                                  64 |
| dropout                                  0.15776 |
| lr                     

(train_mnist pid=3421) 2024-12-05 14:27:01.101091: W tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:47] Overriding orig_value setting because the TF_FORCE_GPU_ALLOW_GROWTH environment variable is set. Original config value was 0.
(train_mnist pid=3421) WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
(train_mnist pid=3421) I0000 00:00:1733408824.377891    3635 service.cc:146] XLA service 0x7c155c017440 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
(train_mnist pid=3421) I0000 00:00:1733408824.377951    3635 service.cc:154]   StreamExecutor device (0): NVIDIA L4, Compute Capability 8.9
(pid=3422) 2024-12-05 14:26:56.830723: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:485] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
(pid=3422) 2024-12-05 14:26:56.852288: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:8


Trial status: 2 RUNNING | 25 PENDING
Current time: 2024-12-05 14:27:25. Total running time: 30s
Logical resource usage: 2.0/12 CPUs, 1.0/1 GPUs (0.0/1.0 accelerator_type:L4)
+----------------------------------------------------------------------------------------+
| Trial name                status       dropout     conv_filters      lr     batch_size |
+----------------------------------------------------------------------------------------+
| train_mnist_f80bd_00000   RUNNING    0.0800099               64   0.001             64 |
| train_mnist_f80bd_00001   RUNNING    0.157755                64   0.001            128 |
| train_mnist_f80bd_00002   PENDING    0.56265                 64   0.001            256 |
| train_mnist_f80bd_00003   PENDING    0.0198027              128   0.001             64 |
| train_mnist_f80bd_00004   PENDING    0.76506                128   0.001            128 |
| train_mnist_f80bd_00005   PENDING    0.628439               128   0.001            256 |
| trai

(pid=4892) 2024-12-05 14:27:45.653519: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:485] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
(pid=4892) 2024-12-05 14:27:45.678801: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:8454] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
(pid=4892) 2024-12-05 14:27:45.686125: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1452] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
(train_mnist pid=3422) I0000 00:00:1733408834.270943    3639 device_compiler.h:188] Compiled cluster using XLA!  This line is logged at most once for the lifetime of the process.
(pid=4892) 2024-12-05 14:27:47.050764: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT



Trial train_mnist_f80bd_00002 started with configuration:
+--------------------------------------------------+
| Trial train_mnist_f80bd_00002 config             |
+--------------------------------------------------+
| batch_size                                   256 |
| conv_filters                                  64 |
| dropout                                  0.56265 |
| lr                                         0.001 |
+--------------------------------------------------+


(train_mnist pid=4892) 2024-12-05 14:27:48.988422: W tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:47] Overriding orig_value setting because the TF_FORCE_GPU_ALLOW_GROWTH environment variable is set. Original config value was 0.
(train_mnist pid=4892) WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
(train_mnist pid=4892) I0000 00:00:1733408871.916203    5087 service.cc:146] XLA service 0x793c24017f70 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
(train_mnist pid=4892) I0000 00:00:1733408871.916259    5087 service.cc:154]   StreamExecutor device (0): NVIDIA L4, Compute Capability 8.9



Trial train_mnist_f80bd_00000 finished iteration 1 at 2024-12-05 14:27:52. Total running time: 57s
+--------------------------------------------------+
| Trial train_mnist_f80bd_00000 result             |
+--------------------------------------------------+
| checkpoint_dir_name                              |
| time_this_iter_s                         53.1455 |
| time_total_s                             53.1455 |
| training_iteration                             1 |
| mean_accuracy                            0.99758 |
+--------------------------------------------------+

Trial train_mnist_f80bd_00000 completed after 1 iterations at 2024-12-05 14:27:52. Total running time: 57s

Trial status: 2 TERMINATED | 1 RUNNING | 24 PENDING
Current time: 2024-12-05 14:27:55. Total running time: 1min 0s
Logical resource usage: 2.0/12 CPUs, 1.0/1 GPUs (0.0/1.0 accelerator_type:L4)
Current best trial: f80bd_00001 with mean_accuracy=0.9979666471481323 and params={'conv_filters': 64, 'lr': 0.001, 'dropo

(pid=5233) 2024-12-05 14:27:55.728114: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:485] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
(pid=5233) 2024-12-05 14:27:55.761735: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:8454] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
(pid=5233) 2024-12-05 14:27:55.768290: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1452] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
(pid=5233) 2024-12-05 14:27:57.024695: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT



Trial train_mnist_f80bd_00003 started with configuration:
+-------------------------------------------------+
| Trial train_mnist_f80bd_00003 config            |
+-------------------------------------------------+
| batch_size                                   64 |
| conv_filters                                128 |
| dropout                                  0.0198 |
| lr                                        0.001 |
+-------------------------------------------------+


(train_mnist pid=5233) 2024-12-05 14:27:58.854222: W tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:47] Overriding orig_value setting because the TF_FORCE_GPU_ALLOW_GROWTH environment variable is set. Original config value was 0.
(train_mnist pid=4892) I0000 00:00:1733408879.831390    5087 device_compiler.h:188] Compiled cluster using XLA!  This line is logged at most once for the lifetime of the process.
(train_mnist pid=5233) WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
(train_mnist pid=5233) I0000 00:00:1733408881.819963    5392 service.cc:146] XLA service 0x7fcb5c003970 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
(train_mnist pid=5233) I0000 00:00:1733408881.820042    5392 service.cc:154]   StreamExecutor device (0): NVIDIA L4, Compute Capability 8.9
(train_mnist pid=5233) I0000 00:00:1733408889.301527    5392 device_compiler.h:188] Compiled cluster using XLA!  This line is logged at most


Trial status: 2 TERMINATED | 2 RUNNING | 23 PENDING
Current time: 2024-12-05 14:28:25. Total running time: 1min 30s
Logical resource usage: 2.0/12 CPUs, 1.0/1 GPUs (0.0/1.0 accelerator_type:L4)
Current best trial: f80bd_00001 with mean_accuracy=0.9979666471481323 and params={'conv_filters': 64, 'lr': 0.001, 'dropout': 0.1577551489310799, 'batch_size': 128}
+----------------------------------------------------------------------------------------------------------------------------------+
| Trial name                status          dropout     conv_filters      lr     batch_size        acc     iter     total time (s) |
+----------------------------------------------------------------------------------------------------------------------------------+
| train_mnist_f80bd_00002   RUNNING      0.56265                  64   0.001            256                                        |
| train_mnist_f80bd_00003   RUNNING      0.0198027               128   0.001             64                 

(pid=6308) 2024-12-05 14:28:31.562498: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:485] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
(pid=6308) 2024-12-05 14:28:31.584314: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:8454] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
(pid=6308) 2024-12-05 14:28:31.590757: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1452] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
(pid=6308) 2024-12-05 14:28:32.921328: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT



Trial train_mnist_f80bd_00004 started with configuration:
+--------------------------------------------------+
| Trial train_mnist_f80bd_00004 config             |
+--------------------------------------------------+
| batch_size                                   128 |
| conv_filters                                 128 |
| dropout                                  0.76506 |
| lr                                         0.001 |
+--------------------------------------------------+


(train_mnist pid=6308) 2024-12-05 14:28:34.943849: W tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:47] Overriding orig_value setting because the TF_FORCE_GPU_ALLOW_GROWTH environment variable is set. Original config value was 0.
(train_mnist pid=6308) WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
(train_mnist pid=6308) I0000 00:00:1733408917.797968    6472 service.cc:146] XLA service 0x79b47c005b80 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
(train_mnist pid=6308) I0000 00:00:1733408917.798017    6472 service.cc:154]   StreamExecutor device (0): NVIDIA L4, Compute Capability 8.9
(train_mnist pid=6308) I0000 00:00:1733408925.274304    6472 device_compiler.h:188] Compiled cluster using XLA!  This line is logged at most once for the lifetime of the process.



Trial status: 3 TERMINATED | 2 RUNNING | 22 PENDING
Current time: 2024-12-05 14:28:55. Total running time: 2min 0s
Logical resource usage: 2.0/12 CPUs, 1.0/1 GPUs (0.0/1.0 accelerator_type:L4)
Current best trial: f80bd_00001 with mean_accuracy=0.9979666471481323 and params={'conv_filters': 64, 'lr': 0.001, 'dropout': 0.1577551489310799, 'batch_size': 128}
+----------------------------------------------------------------------------------------------------------------------------------+
| Trial name                status          dropout     conv_filters      lr     batch_size        acc     iter     total time (s) |
+----------------------------------------------------------------------------------------------------------------------------------+
| train_mnist_f80bd_00003   RUNNING      0.0198027               128   0.001             64                                        |
| train_mnist_f80bd_00004   RUNNING      0.76506                 128   0.001            128                  

(pid=7164) 2024-12-05 14:29:07.505546: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:485] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
(pid=7164) 2024-12-05 14:29:07.527893: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:8454] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
(pid=7164) 2024-12-05 14:29:07.534309: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1452] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
(pid=7164) 2024-12-05 14:29:08.766144: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT



Trial train_mnist_f80bd_00005 started with configuration:
+--------------------------------------------------+
| Trial train_mnist_f80bd_00005 config             |
+--------------------------------------------------+
| batch_size                                   256 |
| conv_filters                                 128 |
| dropout                                  0.62844 |
| lr                                         0.001 |
+--------------------------------------------------+


(train_mnist pid=7164) 2024-12-05 14:29:10.654308: W tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:47] Overriding orig_value setting because the TF_FORCE_GPU_ALLOW_GROWTH environment variable is set. Original config value was 0.
(train_mnist pid=7164) WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
(train_mnist pid=7164) I0000 00:00:1733408953.434473    7330 service.cc:146] XLA service 0x79f8ac0050b0 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
(train_mnist pid=7164) I0000 00:00:1733408953.434520    7330 service.cc:154]   StreamExecutor device (0): NVIDIA L4, Compute Capability 8.9
(train_mnist pid=7164) I0000 00:00:1733408962.890004    7330 device_compiler.h:188] Compiled cluster using XLA!  This line is logged at most once for the lifetime of the process.



Trial status: 4 TERMINATED | 2 RUNNING | 21 PENDING
Current time: 2024-12-05 14:29:25. Total running time: 2min 30s
Logical resource usage: 2.0/12 CPUs, 1.0/1 GPUs (0.0/1.0 accelerator_type:L4)
Current best trial: f80bd_00001 with mean_accuracy=0.9979666471481323 and params={'conv_filters': 64, 'lr': 0.001, 'dropout': 0.1577551489310799, 'batch_size': 128}
+----------------------------------------------------------------------------------------------------------------------------------+
| Trial name                status          dropout     conv_filters      lr     batch_size        acc     iter     total time (s) |
+----------------------------------------------------------------------------------------------------------------------------------+
| train_mnist_f80bd_00004   RUNNING      0.76506                 128   0.001            128                                        |
| train_mnist_f80bd_00005   RUNNING      0.628439                128   0.001            256                 

(pid=7909) 2024-12-05 14:29:36.637183: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:485] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
(pid=7909) 2024-12-05 14:29:36.673883: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:8454] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
(pid=7909) 2024-12-05 14:29:36.684665: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1452] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
(pid=7909) 2024-12-05 14:29:37.997176: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT



Trial train_mnist_f80bd_00006 started with configuration:
+--------------------------------------------------+
| Trial train_mnist_f80bd_00006 config             |
+--------------------------------------------------+
| batch_size                                    64 |
| conv_filters                                 256 |
| dropout                                  0.40724 |
| lr                                         0.001 |
+--------------------------------------------------+


(train_mnist pid=7909) 2024-12-05 14:29:39.861125: W tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:47] Overriding orig_value setting because the TF_FORCE_GPU_ALLOW_GROWTH environment variable is set. Original config value was 0.
(train_mnist pid=7909) WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
(train_mnist pid=7909) I0000 00:00:1733408982.535671    8060 service.cc:146] XLA service 0x7a90c80067f0 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
(train_mnist pid=7909) I0000 00:00:1733408982.535715    8060 service.cc:154]   StreamExecutor device (0): NVIDIA L4, Compute Capability 8.9
(train_mnist pid=7909) I0000 00:00:1733408990.210453    8060 device_compiler.h:188] Compiled cluster using XLA!  This line is logged at most once for the lifetime of the process.



Trial status: 5 TERMINATED | 2 RUNNING | 20 PENDING
Current time: 2024-12-05 14:29:55. Total running time: 3min 0s
Logical resource usage: 2.0/12 CPUs, 1.0/1 GPUs (0.0/1.0 accelerator_type:L4)
Current best trial: f80bd_00001 with mean_accuracy=0.9979666471481323 and params={'conv_filters': 64, 'lr': 0.001, 'dropout': 0.1577551489310799, 'batch_size': 128}
+----------------------------------------------------------------------------------------------------------------------------------+
| Trial name                status          dropout     conv_filters      lr     batch_size        acc     iter     total time (s) |
+----------------------------------------------------------------------------------------------------------------------------------+
| train_mnist_f80bd_00005   RUNNING      0.628439                128   0.001            256                                        |
| train_mnist_f80bd_00006   RUNNING      0.407241                256   0.001             64                  

(pid=8810) 2024-12-05 14:30:16.502515: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:485] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
(pid=8810) 2024-12-05 14:30:16.524928: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:8454] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
(pid=8810) 2024-12-05 14:30:16.531499: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1452] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
(pid=8810) 2024-12-05 14:30:17.828169: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT



Trial train_mnist_f80bd_00007 started with configuration:
+--------------------------------------------------+
| Trial train_mnist_f80bd_00007 config             |
+--------------------------------------------------+
| batch_size                                   128 |
| conv_filters                                 256 |
| dropout                                  0.00844 |
| lr                                         0.001 |
+--------------------------------------------------+


(train_mnist pid=8810) 2024-12-05 14:30:19.772501: W tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:47] Overriding orig_value setting because the TF_FORCE_GPU_ALLOW_GROWTH environment variable is set. Original config value was 0.
(train_mnist pid=8810) WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
(train_mnist pid=8810) I0000 00:00:1733409022.504539    8908 service.cc:146] XLA service 0x7a7a54006240 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
(train_mnist pid=8810) I0000 00:00:1733409022.504589    8908 service.cc:154]   StreamExecutor device (0): NVIDIA L4, Compute Capability 8.9



Trial status: 6 TERMINATED | 2 RUNNING | 19 PENDING
Current time: 2024-12-05 14:30:25. Total running time: 3min 30s
Logical resource usage: 2.0/12 CPUs, 1.0/1 GPUs (0.0/1.0 accelerator_type:L4)
Current best trial: f80bd_00001 with mean_accuracy=0.9979666471481323 and params={'conv_filters': 64, 'lr': 0.001, 'dropout': 0.1577551489310799, 'batch_size': 128}
+----------------------------------------------------------------------------------------------------------------------------------+
| Trial name                status          dropout     conv_filters      lr     batch_size        acc     iter     total time (s) |
+----------------------------------------------------------------------------------------------------------------------------------+
| train_mnist_f80bd_00006   RUNNING      0.407241                256   0.001             64                                        |
| train_mnist_f80bd_00007   RUNNING      0.00844249              256   0.001            128                 

(train_mnist pid=8810) I0000 00:00:1733409033.229955    8908 device_compiler.h:188] Compiled cluster using XLA!  This line is logged at most once for the lifetime of the process.


Trial status: 6 TERMINATED | 2 RUNNING | 19 PENDING
Current time: 2024-12-05 14:30:55. Total running time: 4min 0s
Logical resource usage: 2.0/12 CPUs, 1.0/1 GPUs (0.0/1.0 accelerator_type:L4)
Current best trial: f80bd_00001 with mean_accuracy=0.9979666471481323 and params={'conv_filters': 64, 'lr': 0.001, 'dropout': 0.1577551489310799, 'batch_size': 128}
+----------------------------------------------------------------------------------------------------------------------------------+
| Trial name                status          dropout     conv_filters      lr     batch_size        acc     iter     total time (s) |
+----------------------------------------------------------------------------------------------------------------------------------+
| train_mnist_f80bd_00006   RUNNING      0.407241                256   0.001             64                                        |
| train_mnist_f80bd_00007   RUNNING      0.00844249              256   0.001            128                   

(pid=10404) 2024-12-05 14:32:42.497881: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:485] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
(pid=10404) 2024-12-05 14:32:42.519434: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:8454] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
(pid=10404) 2024-12-05 14:32:42.526099: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1452] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
(pid=10404) 2024-12-05 14:32:43.740639: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT



Trial train_mnist_f80bd_00008 started with configuration:
+--------------------------------------------------+
| Trial train_mnist_f80bd_00008 config             |
+--------------------------------------------------+
| batch_size                                   256 |
| conv_filters                                 256 |
| dropout                                  0.94513 |
| lr                                         0.001 |
+--------------------------------------------------+


(train_mnist pid=10404) 2024-12-05 14:32:45.583810: W tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:47] Overriding orig_value setting because the TF_FORCE_GPU_ALLOW_GROWTH environment variable is set. Original config value was 0.
(train_mnist pid=10404) WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
(train_mnist pid=10404) I0000 00:00:1733409168.322337   10534 service.cc:146] XLA service 0x78d9d8003fc0 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
(train_mnist pid=10404) I0000 00:00:1733409168.322386   10534 service.cc:154]   StreamExecutor device (0): NVIDIA L4, Compute Capability 8.9



Trial status: 7 TERMINATED | 2 RUNNING | 18 PENDING
Current time: 2024-12-05 14:32:55. Total running time: 6min 0s
Logical resource usage: 2.0/12 CPUs, 1.0/1 GPUs (0.0/1.0 accelerator_type:L4)
Current best trial: f80bd_00001 with mean_accuracy=0.9979666471481323 and params={'conv_filters': 64, 'lr': 0.001, 'dropout': 0.1577551489310799, 'batch_size': 128}
+----------------------------------------------------------------------------------------------------------------------------------+
| Trial name                status          dropout     conv_filters      lr     batch_size        acc     iter     total time (s) |
+----------------------------------------------------------------------------------------------------------------------------------+
| train_mnist_f80bd_00007   RUNNING      0.00844249              256   0.001            128                                        |
| train_mnist_f80bd_00008   RUNNING      0.945128                256   0.001            256                  

(train_mnist pid=10404) I0000 00:00:1733409182.864985   10534 device_compiler.h:188] Compiled cluster using XLA!  This line is logged at most once for the lifetime of the process.
(pid=10785) 2024-12-05 14:33:03.512898: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:485] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
(pid=10785) 2024-12-05 14:33:03.534294: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:8454] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
(pid=10785) 2024-12-05 14:33:03.540768: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1452] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
(pid=10785) 2024-12-05 14:33:04.789751: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT



Trial train_mnist_f80bd_00009 started with configuration:
+--------------------------------------------------+
| Trial train_mnist_f80bd_00009 config             |
+--------------------------------------------------+
| batch_size                                    64 |
| conv_filters                                  64 |
| dropout                                  0.49849 |
| lr                                          0.01 |
+--------------------------------------------------+


(train_mnist pid=10785) 2024-12-05 14:33:06.640251: W tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:47] Overriding orig_value setting because the TF_FORCE_GPU_ALLOW_GROWTH environment variable is set. Original config value was 0.
(train_mnist pid=10785) WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
(train_mnist pid=10785) I0000 00:00:1733409189.391745   10886 service.cc:146] XLA service 0x7ed2dc005370 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
(train_mnist pid=10785) I0000 00:00:1733409189.391794   10886 service.cc:154]   StreamExecutor device (0): NVIDIA L4, Compute Capability 8.9
(train_mnist pid=10785) I0000 00:00:1733409198.090984   10886 device_compiler.h:188] Compiled cluster using XLA!  This line is logged at most once for the lifetime of the process.



Trial status: 8 TERMINATED | 2 RUNNING | 17 PENDING
Current time: 2024-12-05 14:33:25. Total running time: 6min 31s
Logical resource usage: 2.0/12 CPUs, 1.0/1 GPUs (0.0/1.0 accelerator_type:L4)
Current best trial: f80bd_00007 with mean_accuracy=0.9981333613395691 and params={'conv_filters': 256, 'lr': 0.001, 'dropout': 0.00844249100058081, 'batch_size': 128}
+---------------------------------------------------------------------------------------------------------------------------------+
| Trial name                status         dropout     conv_filters      lr     batch_size        acc     iter     total time (s) |
+---------------------------------------------------------------------------------------------------------------------------------+
| train_mnist_f80bd_00008   RUNNING      0.945128               256   0.001            256                                        |
| train_mnist_f80bd_00009   RUNNING      0.498486                64   0.01              64                    

(pid=12247) 2024-12-05 14:34:31.498805: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:485] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
(pid=12247) 2024-12-05 14:34:31.520488: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:8454] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
(pid=12247) 2024-12-05 14:34:31.527097: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1452] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
(pid=12247) 2024-12-05 14:34:32.760514: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT



Trial train_mnist_f80bd_00010 started with configuration:
+--------------------------------------------------+
| Trial train_mnist_f80bd_00010 config             |
+--------------------------------------------------+
| batch_size                                   128 |
| conv_filters                                  64 |
| dropout                                  0.80598 |
| lr                                          0.01 |
+--------------------------------------------------+


(train_mnist pid=12247) 2024-12-05 14:34:34.671377: W tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:47] Overriding orig_value setting because the TF_FORCE_GPU_ALLOW_GROWTH environment variable is set. Original config value was 0.
(train_mnist pid=12247) WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
(train_mnist pid=12247) I0000 00:00:1733409277.380921   12377 service.cc:146] XLA service 0x7856ac006640 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
(train_mnist pid=12247) I0000 00:00:1733409277.380969   12377 service.cc:154]   StreamExecutor device (0): NVIDIA L4, Compute Capability 8.9
(train_mnist pid=12247) I0000 00:00:1733409286.552222   12377 device_compiler.h:188] Compiled cluster using XLA!  This line is logged at most once for the lifetime of the process.



Trial train_mnist_f80bd_00008 finished iteration 1 at 2024-12-05 14:34:47. Total running time: 7min 52s
+--------------------------------------------------+
| Trial train_mnist_f80bd_00008 result             |
+--------------------------------------------------+
| checkpoint_dir_name                              |
| time_this_iter_s                         122.647 |
| time_total_s                             122.647 |
| training_iteration                             1 |
| mean_accuracy                            0.59305 |
+--------------------------------------------------+

Trial train_mnist_f80bd_00008 completed after 1 iterations at 2024-12-05 14:34:47. Total running time: 7min 52s


(pid=12613) 2024-12-05 14:34:50.077588: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:485] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
(pid=12613) 2024-12-05 14:34:50.114662: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:8454] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
(pid=12613) 2024-12-05 14:34:50.125623: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1452] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
(pid=12613) 2024-12-05 14:34:51.809248: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT



Trial train_mnist_f80bd_00011 started with configuration:
+--------------------------------------------------+
| Trial train_mnist_f80bd_00011 config             |
+--------------------------------------------------+
| batch_size                                   256 |
| conv_filters                                  64 |
| dropout                                  0.83154 |
| lr                                          0.01 |
+--------------------------------------------------+


(train_mnist pid=12613) 2024-12-05 14:34:53.640790: W tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:47] Overriding orig_value setting because the TF_FORCE_GPU_ALLOW_GROWTH environment variable is set. Original config value was 0.



Trial status: 10 TERMINATED | 2 RUNNING | 15 PENDING
Current time: 2024-12-05 14:34:55. Total running time: 8min 1s
Logical resource usage: 2.0/12 CPUs, 1.0/1 GPUs (0.0/1.0 accelerator_type:L4)
Current best trial: f80bd_00007 with mean_accuracy=0.9981333613395691 and params={'conv_filters': 256, 'lr': 0.001, 'dropout': 0.00844249100058081, 'batch_size': 128}
+---------------------------------------------------------------------------------------------------------------------------------+
| Trial name                status         dropout     conv_filters      lr     batch_size        acc     iter     total time (s) |
+---------------------------------------------------------------------------------------------------------------------------------+
| train_mnist_f80bd_00010   RUNNING      0.805977                64   0.01             128                                        |
| train_mnist_f80bd_00011   RUNNING      0.831537                64   0.01             256                    

(train_mnist pid=12613) WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
(train_mnist pid=12613) I0000 00:00:1733409296.373924   12769 service.cc:146] XLA service 0x7c36b4004f00 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
(train_mnist pid=12613) I0000 00:00:1733409296.373975   12769 service.cc:154]   StreamExecutor device (0): NVIDIA L4, Compute Capability 8.9
(train_mnist pid=12613) I0000 00:00:1733409304.586698   12769 device_compiler.h:188] Compiled cluster using XLA!  This line is logged at most once for the lifetime of the process.



Trial train_mnist_f80bd_00010 finished iteration 1 at 2024-12-05 14:35:17. Total running time: 8min 23s
+--------------------------------------------------+
| Trial train_mnist_f80bd_00010 result             |
+--------------------------------------------------+
| checkpoint_dir_name                              |
| time_this_iter_s                         43.7985 |
| time_total_s                             43.7985 |
| training_iteration                             1 |
| mean_accuracy                            0.11138 |
+--------------------------------------------------+

Trial train_mnist_f80bd_00010 completed after 1 iterations at 2024-12-05 14:35:17. Total running time: 8min 23s


(pid=13660) 2024-12-05 14:35:20.564620: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:485] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
(pid=13660) 2024-12-05 14:35:20.586941: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:8454] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
(pid=13660) 2024-12-05 14:35:20.593595: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1452] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
(pid=13660) 2024-12-05 14:35:21.818837: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT



Trial train_mnist_f80bd_00012 started with configuration:
+--------------------------------------------------+
| Trial train_mnist_f80bd_00012 config             |
+--------------------------------------------------+
| batch_size                                    64 |
| conv_filters                                 128 |
| dropout                                  0.50194 |
| lr                                          0.01 |
+--------------------------------------------------+


(train_mnist pid=13660) 2024-12-05 14:35:23.685657: W tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:47] Overriding orig_value setting because the TF_FORCE_GPU_ALLOW_GROWTH environment variable is set. Original config value was 0.



Trial status: 11 TERMINATED | 2 RUNNING | 14 PENDING
Current time: 2024-12-05 14:35:25. Total running time: 8min 31s
Logical resource usage: 2.0/12 CPUs, 1.0/1 GPUs (0.0/1.0 accelerator_type:L4)
Current best trial: f80bd_00007 with mean_accuracy=0.9981333613395691 and params={'conv_filters': 256, 'lr': 0.001, 'dropout': 0.00844249100058081, 'batch_size': 128}
+---------------------------------------------------------------------------------------------------------------------------------+
| Trial name                status         dropout     conv_filters      lr     batch_size        acc     iter     total time (s) |
+---------------------------------------------------------------------------------------------------------------------------------+
| train_mnist_f80bd_00011   RUNNING      0.831537                64   0.01             256                                        |
| train_mnist_f80bd_00012   RUNNING      0.501939               128   0.01              64                   

(train_mnist pid=13660) WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
(train_mnist pid=13660) I0000 00:00:1733409326.496626   13883 service.cc:146] XLA service 0x7926d4006030 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
(train_mnist pid=13660) I0000 00:00:1733409326.496678   13883 service.cc:154]   StreamExecutor device (0): NVIDIA L4, Compute Capability 8.9



Trial train_mnist_f80bd_00011 finished iteration 1 at 2024-12-05 14:35:29. Total running time: 8min 34s
+--------------------------------------------------+
| Trial train_mnist_f80bd_00011 result             |
+--------------------------------------------------+
| checkpoint_dir_name                              |
| time_this_iter_s                         36.4322 |
| time_total_s                             36.4322 |
| training_iteration                             1 |
| mean_accuracy                            0.92167 |
+--------------------------------------------------+

Trial train_mnist_f80bd_00011 completed after 1 iterations at 2024-12-05 14:35:29. Total running time: 8min 34s


(pid=14175) 2024-12-05 14:35:31.548467: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:485] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
(pid=14175) 2024-12-05 14:35:31.570294: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:8454] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
(pid=14175) 2024-12-05 14:35:31.577022: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1452] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
(train_mnist pid=13660) I0000 00:00:1733409332.106029   13883 device_compiler.h:188] Compiled cluster using XLA!  This line is logged at most once for the lifetime of the process.
(pid=14175) 2024-12-05 14:35:32.794772: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT



Trial train_mnist_f80bd_00013 started with configuration:
+--------------------------------------------------+
| Trial train_mnist_f80bd_00013 config             |
+--------------------------------------------------+
| batch_size                                   128 |
| conv_filters                                 128 |
| dropout                                  0.41588 |
| lr                                          0.01 |
+--------------------------------------------------+


(train_mnist pid=14175) 2024-12-05 14:35:34.691711: W tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:47] Overriding orig_value setting because the TF_FORCE_GPU_ALLOW_GROWTH environment variable is set. Original config value was 0.
(train_mnist pid=14175) WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
(train_mnist pid=14175) I0000 00:00:1733409337.774772   14272 service.cc:146] XLA service 0x7b0368005eb0 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
(train_mnist pid=14175) I0000 00:00:1733409337.774845   14272 service.cc:154]   StreamExecutor device (0): NVIDIA L4, Compute Capability 8.9
(train_mnist pid=14175) I0000 00:00:1733409345.306314   14272 device_compiler.h:188] Compiled cluster using XLA!  This line is logged at most once for the lifetime of the process.



Trial status: 12 TERMINATED | 2 RUNNING | 13 PENDING
Current time: 2024-12-05 14:35:56. Total running time: 9min 1s
Logical resource usage: 2.0/12 CPUs, 1.0/1 GPUs (0.0/1.0 accelerator_type:L4)
Current best trial: f80bd_00007 with mean_accuracy=0.9981333613395691 and params={'conv_filters': 256, 'lr': 0.001, 'dropout': 0.00844249100058081, 'batch_size': 128}
+---------------------------------------------------------------------------------------------------------------------------------+
| Trial name                status         dropout     conv_filters      lr     batch_size        acc     iter     total time (s) |
+---------------------------------------------------------------------------------------------------------------------------------+
| train_mnist_f80bd_00012   RUNNING      0.501939               128   0.01              64                                        |
| train_mnist_f80bd_00013   RUNNING      0.415879               128   0.01             128                    

(pid=15612) 2024-12-05 14:36:37.588301: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:485] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
(pid=15612) 2024-12-05 14:36:37.611873: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:8454] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
(pid=15612) 2024-12-05 14:36:37.618298: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1452] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered



Trial train_mnist_f80bd_00012 finished iteration 1 at 2024-12-05 14:36:37. Total running time: 9min 42s
+--------------------------------------------------+
| Trial train_mnist_f80bd_00012 result             |
+--------------------------------------------------+
| checkpoint_dir_name                              |
| time_this_iter_s                         74.5761 |
| time_total_s                             74.5761 |
| training_iteration                             1 |
| mean_accuracy                            0.97082 |
+--------------------------------------------------+

Trial train_mnist_f80bd_00012 completed after 1 iterations at 2024-12-05 14:36:37. Total running time: 9min 42s


(pid=15612) 2024-12-05 14:36:38.805727: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT



Trial train_mnist_f80bd_00014 started with configuration:
+--------------------------------------------------+
| Trial train_mnist_f80bd_00014 config             |
+--------------------------------------------------+
| batch_size                                   256 |
| conv_filters                                 128 |
| dropout                                  0.22519 |
| lr                                          0.01 |
+--------------------------------------------------+


(train_mnist pid=15612) 2024-12-05 14:36:40.613716: W tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:47] Overriding orig_value setting because the TF_FORCE_GPU_ALLOW_GROWTH environment variable is set. Original config value was 0.



Trial train_mnist_f80bd_00015 started with configuration:
+-------------------------------------------------+
| Trial train_mnist_f80bd_00015 config            |
+-------------------------------------------------+
| batch_size                                   64 |
| conv_filters                                256 |
| dropout                                  0.3861 |
| lr                                         0.01 |
+-------------------------------------------------+


(pid=15682) 2024-12-05 14:36:39.525228: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:485] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
(train_mnist pid=15612) WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
(train_mnist pid=15612) I0000 00:00:1733409403.235173   15772 service.cc:146] XLA service 0x7e10b4003fe0 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
(train_mnist pid=15612) I0000 00:00:1733409403.235215   15772 service.cc:154]   StreamExecutor device (0): NVIDIA L4, Compute Capability 8.9
(pid=15682) 2024-12-05 14:36:39.546993: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:8454] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
(pid=15682) 2024-12-05 14:36:39.553489: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1452] Unabl


Trial status: 14 TERMINATED | 2 RUNNING | 11 PENDING
Current time: 2024-12-05 14:36:56. Total running time: 10min 1s
Logical resource usage: 2.0/12 CPUs, 1.0/1 GPUs (0.0/1.0 accelerator_type:L4)
Current best trial: f80bd_00007 with mean_accuracy=0.9981333613395691 and params={'conv_filters': 256, 'lr': 0.001, 'dropout': 0.00844249100058081, 'batch_size': 128}
+---------------------------------------------------------------------------------------------------------------------------------+
| Trial name                status         dropout     conv_filters      lr     batch_size        acc     iter     total time (s) |
+---------------------------------------------------------------------------------------------------------------------------------+
| train_mnist_f80bd_00014   RUNNING      0.225188               128   0.01             256                                        |
| train_mnist_f80bd_00015   RUNNING      0.386098               256   0.01              64                   

(pid=17115) 2024-12-05 14:37:58.546170: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:485] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
(pid=17115) 2024-12-05 14:37:58.569302: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:8454] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
(pid=17115) 2024-12-05 14:37:58.575894: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1452] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
(train_mnist pid=15682) I0000 00:00:1733409412.801420   15856 device_compiler.h:188] Compiled cluster using XLA!  This line is logged at most once for the lifetime of the process.
(pid=17115) 2024-12-05 14:37:59.775439: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT



Trial train_mnist_f80bd_00016 started with configuration:
+--------------------------------------------------+
| Trial train_mnist_f80bd_00016 config             |
+--------------------------------------------------+
| batch_size                                   128 |
| conv_filters                                 256 |
| dropout                                  0.07781 |
| lr                                          0.01 |
+--------------------------------------------------+


(train_mnist pid=17115) 2024-12-05 14:38:01.616102: W tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:47] Overriding orig_value setting because the TF_FORCE_GPU_ALLOW_GROWTH environment variable is set. Original config value was 0.
(train_mnist pid=17115) WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
(train_mnist pid=17115) I0000 00:00:1733409484.355862   17247 service.cc:146] XLA service 0x7b084c004a30 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
(train_mnist pid=17115) I0000 00:00:1733409484.355914   17247 service.cc:154]   StreamExecutor device (0): NVIDIA L4, Compute Capability 8.9
(train_mnist pid=17115) I0000 00:00:1733409495.804854   17247 device_compiler.h:188] Compiled cluster using XLA!  This line is logged at most once for the lifetime of the process.



Trial status: 15 TERMINATED | 2 RUNNING | 10 PENDING
Current time: 2024-12-05 14:38:26. Total running time: 11min 31s
Logical resource usage: 2.0/12 CPUs, 1.0/1 GPUs (0.0/1.0 accelerator_type:L4)
Current best trial: f80bd_00007 with mean_accuracy=0.9981333613395691 and params={'conv_filters': 256, 'lr': 0.001, 'dropout': 0.00844249100058081, 'batch_size': 128}
+---------------------------------------------------------------------------------------------------------------------------------+
| Trial name                status         dropout     conv_filters      lr     batch_size        acc     iter     total time (s) |
+---------------------------------------------------------------------------------------------------------------------------------+
| train_mnist_f80bd_00015   RUNNING      0.386098               256   0.01              64                                        |
| train_mnist_f80bd_00016   RUNNING      0.0778066              256   0.01             128                  

(pid=18195) 2024-12-05 14:39:25.553213: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:485] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
(pid=18195) 2024-12-05 14:39:25.575285: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:8454] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
(pid=18195) 2024-12-05 14:39:25.582014: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1452] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered



Trial status: 16 TERMINATED | 1 RUNNING | 10 PENDING
Current time: 2024-12-05 14:39:26. Total running time: 12min 31s
Logical resource usage: 2.0/12 CPUs, 1.0/1 GPUs (0.0/1.0 accelerator_type:L4)
Current best trial: f80bd_00007 with mean_accuracy=0.9981333613395691 and params={'conv_filters': 256, 'lr': 0.001, 'dropout': 0.00844249100058081, 'batch_size': 128}
+---------------------------------------------------------------------------------------------------------------------------------+
| Trial name                status         dropout     conv_filters      lr     batch_size        acc     iter     total time (s) |
+---------------------------------------------------------------------------------------------------------------------------------+
| train_mnist_f80bd_00016   RUNNING      0.0778066              256   0.01             128                                        |
| train_mnist_f80bd_00000   TERMINATED   0.0800099               64   0.001             64   0.997583       

(pid=18195) 2024-12-05 14:39:26.788010: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT



Trial train_mnist_f80bd_00017 started with configuration:
+-------------------------------------------------+
| Trial train_mnist_f80bd_00017 config            |
+-------------------------------------------------+
| batch_size                                  256 |
| conv_filters                                256 |
| dropout                                  0.3638 |
| lr                                         0.01 |
+-------------------------------------------------+


(train_mnist pid=18195) 2024-12-05 14:39:28.664741: W tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:47] Overriding orig_value setting because the TF_FORCE_GPU_ALLOW_GROWTH environment variable is set. Original config value was 0.
(train_mnist pid=18195) WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
(train_mnist pid=18195) I0000 00:00:1733409571.365072   18324 service.cc:146] XLA service 0x789ac8004e10 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
(train_mnist pid=18195) I0000 00:00:1733409571.365120   18324 service.cc:154]   StreamExecutor device (0): NVIDIA L4, Compute Capability 8.9
(train_mnist pid=18195) I0000 00:00:1733409586.182305   18324 device_compiler.h:188] Compiled cluster using XLA!  This line is logged at most once for the lifetime of the process.



Trial status: 16 TERMINATED | 2 RUNNING | 9 PENDING
Current time: 2024-12-05 14:39:56. Total running time: 13min 1s
Logical resource usage: 2.0/12 CPUs, 1.0/1 GPUs (0.0/1.0 accelerator_type:L4)
Current best trial: f80bd_00007 with mean_accuracy=0.9981333613395691 and params={'conv_filters': 256, 'lr': 0.001, 'dropout': 0.00844249100058081, 'batch_size': 128}
+---------------------------------------------------------------------------------------------------------------------------------+
| Trial name                status         dropout     conv_filters      lr     batch_size        acc     iter     total time (s) |
+---------------------------------------------------------------------------------------------------------------------------------+
| train_mnist_f80bd_00016   RUNNING      0.0778066              256   0.01             128                                        |
| train_mnist_f80bd_00017   RUNNING      0.363803               256   0.01             256                    

(pid=19143) 2024-12-05 14:40:39.603154: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:485] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
(pid=19143) 2024-12-05 14:40:39.624737: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:8454] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
(pid=19143) 2024-12-05 14:40:39.631484: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1452] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
(pid=19143) 2024-12-05 14:40:40.884907: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT



Trial train_mnist_f80bd_00018 started with configuration:
+-------------------------------------------------+
| Trial train_mnist_f80bd_00018 config            |
+-------------------------------------------------+
| batch_size                                   64 |
| conv_filters                                 64 |
| dropout                                  0.3989 |
| lr                                          0.1 |
+-------------------------------------------------+


(train_mnist pid=19143) 2024-12-05 14:40:42.747714: W tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:47] Overriding orig_value setting because the TF_FORCE_GPU_ALLOW_GROWTH environment variable is set. Original config value was 0.
(train_mnist pid=19143) WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
(train_mnist pid=19143) I0000 00:00:1733409645.412869   19275 service.cc:146] XLA service 0x7b31c4004a50 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
(train_mnist pid=19143) I0000 00:00:1733409645.412912   19275 service.cc:154]   StreamExecutor device (0): NVIDIA L4, Compute Capability 8.9
(train_mnist pid=19143) I0000 00:00:1733409653.148959   19275 device_compiler.h:188] Compiled cluster using XLA!  This line is logged at most once for the lifetime of the process.



Trial status: 17 TERMINATED | 2 RUNNING | 8 PENDING
Current time: 2024-12-05 14:40:56. Total running time: 14min 1s
Logical resource usage: 2.0/12 CPUs, 1.0/1 GPUs (0.0/1.0 accelerator_type:L4)
Current best trial: f80bd_00007 with mean_accuracy=0.9981333613395691 and params={'conv_filters': 256, 'lr': 0.001, 'dropout': 0.00844249100058081, 'batch_size': 128}
+---------------------------------------------------------------------------------------------------------------------------------+
| Trial name                status         dropout     conv_filters      lr     batch_size        acc     iter     total time (s) |
+---------------------------------------------------------------------------------------------------------------------------------+
| train_mnist_f80bd_00017   RUNNING      0.363803               256   0.01             256                                        |
| train_mnist_f80bd_00018   RUNNING      0.398897                64   0.1               64                    

(pid=20284) 2024-12-05 14:41:45.684915: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:485] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
(pid=20284) 2024-12-05 14:41:45.707189: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:8454] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
(pid=20284) 2024-12-05 14:41:45.714022: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1452] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
(pid=20284) 2024-12-05 14:41:46.982513: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT



Trial train_mnist_f80bd_00019 started with configuration:
+--------------------------------------------------+
| Trial train_mnist_f80bd_00019 config             |
+--------------------------------------------------+
| batch_size                                   128 |
| conv_filters                                  64 |
| dropout                                  0.12364 |
| lr                                           0.1 |
+--------------------------------------------------+


(train_mnist pid=20284) 2024-12-05 14:41:48.934629: W tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:47] Overriding orig_value setting because the TF_FORCE_GPU_ALLOW_GROWTH environment variable is set. Original config value was 0.



Trial train_mnist_f80bd_00018 finished iteration 1 at 2024-12-05 14:41:51. Total running time: 14min 56s
+--------------------------------------------------+
| Trial train_mnist_f80bd_00018 result             |
+--------------------------------------------------+
| checkpoint_dir_name                              |
| time_this_iter_s                         69.2954 |
| time_total_s                             69.2954 |
| training_iteration                             1 |
| mean_accuracy                            0.10305 |
+--------------------------------------------------+

Trial train_mnist_f80bd_00018 completed after 1 iterations at 2024-12-05 14:41:51. Total running time: 14min 56s


(train_mnist pid=20284) WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
(train_mnist pid=20284) I0000 00:00:1733409711.666232   20462 service.cc:146] XLA service 0x7800600167d0 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
(train_mnist pid=20284) I0000 00:00:1733409711.666279   20462 service.cc:154]   StreamExecutor device (0): NVIDIA L4, Compute Capability 8.9
(pid=20584) 2024-12-05 14:41:54.487516: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:485] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
(pid=20584) 2024-12-05 14:41:54.524116: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:8454] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
(pid=20584) 2024-12-05 14:41:54.535312: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1452] Unabl


Trial status: 19 TERMINATED | 1 RUNNING | 7 PENDING
Current time: 2024-12-05 14:41:56. Total running time: 15min 1s
Logical resource usage: 2.0/12 CPUs, 1.0/1 GPUs (0.0/1.0 accelerator_type:L4)
Current best trial: f80bd_00007 with mean_accuracy=0.9981333613395691 and params={'conv_filters': 256, 'lr': 0.001, 'dropout': 0.00844249100058081, 'batch_size': 128}
+---------------------------------------------------------------------------------------------------------------------------------+
| Trial name                status         dropout     conv_filters      lr     batch_size        acc     iter     total time (s) |
+---------------------------------------------------------------------------------------------------------------------------------+
| train_mnist_f80bd_00019   RUNNING      0.123644                64   0.1              128                                        |
| train_mnist_f80bd_00000   TERMINATED   0.0800099               64   0.001             64   0.997583        1

(train_mnist pid=20584) 2024-12-05 14:41:57.807747: W tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:47] Overriding orig_value setting because the TF_FORCE_GPU_ALLOW_GROWTH environment variable is set. Original config value was 0.
(train_mnist pid=20284) I0000 00:00:1733409718.419239   20462 device_compiler.h:188] Compiled cluster using XLA!  This line is logged at most once for the lifetime of the process.
(train_mnist pid=20584) WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
(train_mnist pid=20584) I0000 00:00:1733409720.889859   20757 service.cc:146] XLA service 0x7cd5b80052b0 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
(train_mnist pid=20584) I0000 00:00:1733409720.889921   20757 service.cc:154]   StreamExecutor device (0): NVIDIA L4, Compute Capability 8.9
(train_mnist pid=20584) I0000 00:00:1733409729.513958   20757 device_compiler.h:188] Compiled cluster using XLA!  This line is logged a


Trial status: 19 TERMINATED | 2 RUNNING | 6 PENDING
Current time: 2024-12-05 14:42:26. Total running time: 15min 31s
Logical resource usage: 2.0/12 CPUs, 1.0/1 GPUs (0.0/1.0 accelerator_type:L4)
Current best trial: f80bd_00007 with mean_accuracy=0.9981333613395691 and params={'conv_filters': 256, 'lr': 0.001, 'dropout': 0.00844249100058081, 'batch_size': 128}
+---------------------------------------------------------------------------------------------------------------------------------+
| Trial name                status         dropout     conv_filters      lr     batch_size        acc     iter     total time (s) |
+---------------------------------------------------------------------------------------------------------------------------------+
| train_mnist_f80bd_00019   RUNNING      0.123644                64   0.1              128                                        |
| train_mnist_f80bd_00020   RUNNING      0.427534                64   0.1              256                   

(pid=21971) 2024-12-05 14:42:34.690788: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:485] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
(pid=21971) 2024-12-05 14:42:34.718266: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:8454] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
(pid=21971) 2024-12-05 14:42:34.729045: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1452] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
(pid=21971) 2024-12-05 14:42:35.947538: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT



Trial train_mnist_f80bd_00021 started with configuration:
+--------------------------------------------------+
| Trial train_mnist_f80bd_00021 config             |
+--------------------------------------------------+
| batch_size                                    64 |
| conv_filters                                 128 |
| dropout                                  0.35041 |
| lr                                           0.1 |
+--------------------------------------------------+


(train_mnist pid=21971) 2024-12-05 14:42:37.842754: W tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:47] Overriding orig_value setting because the TF_FORCE_GPU_ALLOW_GROWTH environment variable is set. Original config value was 0.



Trial train_mnist_f80bd_00022 started with configuration:
+-------------------------------------------------+
| Trial train_mnist_f80bd_00022 config            |
+-------------------------------------------------+
| batch_size                                  128 |
| conv_filters                                128 |
| dropout                                  0.8859 |
| lr                                          0.1 |
+-------------------------------------------------+


(train_mnist pid=21971) WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
(train_mnist pid=21971) I0000 00:00:1733409760.452219   22164 service.cc:146] XLA service 0x7ea194015b60 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
(train_mnist pid=21971) I0000 00:00:1733409760.452272   22164 service.cc:154]   StreamExecutor device (0): NVIDIA L4, Compute Capability 8.9
(pid=22075) 2024-12-05 14:42:36.651131: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:485] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
(pid=22075) 2024-12-05 14:42:36.672614: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:8454] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
(pid=22075) 2024-12-05 14:42:36.679090: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1452] Unabl


Trial status: 21 TERMINATED | 2 RUNNING | 4 PENDING
Current time: 2024-12-05 14:42:56. Total running time: 16min 2s
Logical resource usage: 2.0/12 CPUs, 1.0/1 GPUs (0.0/1.0 accelerator_type:L4)
Current best trial: f80bd_00007 with mean_accuracy=0.9981333613395691 and params={'conv_filters': 256, 'lr': 0.001, 'dropout': 0.00844249100058081, 'batch_size': 128}
+---------------------------------------------------------------------------------------------------------------------------------+
| Trial name                status         dropout     conv_filters      lr     batch_size        acc     iter     total time (s) |
+---------------------------------------------------------------------------------------------------------------------------------+
| train_mnist_f80bd_00021   RUNNING      0.350408               128   0.1               64                                        |
| train_mnist_f80bd_00022   RUNNING      0.885897               128   0.1              128                    

(pid=23576) 2024-12-05 14:43:41.700588: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:485] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
(pid=23576) 2024-12-05 14:43:41.723048: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:8454] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
(pid=23576) 2024-12-05 14:43:41.729528: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1452] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
(train_mnist pid=22075) I0000 00:00:1733409770.386017   22249 device_compiler.h:188] Compiled cluster using XLA!  This line is logged at most once for the lifetime of the process.
(pid=23576) 2024-12-05 14:43:42.997245: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT



Trial train_mnist_f80bd_00023 started with configuration:
+--------------------------------------------------+
| Trial train_mnist_f80bd_00023 config             |
+--------------------------------------------------+
| batch_size                                   256 |
| conv_filters                                 128 |
| dropout                                  0.61539 |
| lr                                           0.1 |
+--------------------------------------------------+


(train_mnist pid=23576) 2024-12-05 14:43:44.915314: W tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:47] Overriding orig_value setting because the TF_FORCE_GPU_ALLOW_GROWTH environment variable is set. Original config value was 0.
(train_mnist pid=23576) WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
(train_mnist pid=23576) I0000 00:00:1733409827.718865   23741 service.cc:146] XLA service 0x7fc8ec003ae0 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
(train_mnist pid=23576) I0000 00:00:1733409827.718913   23741 service.cc:154]   StreamExecutor device (0): NVIDIA L4, Compute Capability 8.9



Trial train_mnist_f80bd_00021 finished iteration 1 at 2024-12-05 14:43:51. Total running time: 16min 56s
+--------------------------------------------------+
| Trial train_mnist_f80bd_00021 result             |
+--------------------------------------------------+
| checkpoint_dir_name                              |
| time_this_iter_s                         74.0165 |
| time_total_s                             74.0165 |
| training_iteration                             1 |
| mean_accuracy                            0.10547 |
+--------------------------------------------------+

Trial train_mnist_f80bd_00021 completed after 1 iterations at 2024-12-05 14:43:51. Total running time: 16min 56s


(pid=23954) 2024-12-05 14:43:53.624729: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:485] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
(pid=23954) 2024-12-05 14:43:53.646492: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:8454] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
(pid=23954) 2024-12-05 14:43:53.653220: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1452] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
(pid=23954) 2024-12-05 14:43:54.868362: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
(train_mnist pid=23576) I0000 00:00:1733409835.298183   23741 device_compiler.h:188] Compiled cluster using XLA!  This line is logged at most once for the lifetime of the process.



Trial train_mnist_f80bd_00024 started with configuration:
+--------------------------------------------------+
| Trial train_mnist_f80bd_00024 config             |
+--------------------------------------------------+
| batch_size                                    64 |
| conv_filters                                 256 |
| dropout                                  0.05123 |
| lr                                           0.1 |
+--------------------------------------------------+


(train_mnist pid=23954) 2024-12-05 14:43:56.713925: W tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:47] Overriding orig_value setting because the TF_FORCE_GPU_ALLOW_GROWTH environment variable is set. Original config value was 0.



Trial status: 23 TERMINATED | 2 RUNNING | 2 PENDING
Current time: 2024-12-05 14:43:56. Total running time: 17min 2s
Logical resource usage: 2.0/12 CPUs, 1.0/1 GPUs (0.0/1.0 accelerator_type:L4)
Current best trial: f80bd_00007 with mean_accuracy=0.9981333613395691 and params={'conv_filters': 256, 'lr': 0.001, 'dropout': 0.00844249100058081, 'batch_size': 128}
+---------------------------------------------------------------------------------------------------------------------------------+
| Trial name                status         dropout     conv_filters      lr     batch_size        acc     iter     total time (s) |
+---------------------------------------------------------------------------------------------------------------------------------+
| train_mnist_f80bd_00023   RUNNING      0.615394               128   0.1              256                                        |
| train_mnist_f80bd_00024   RUNNING      0.0512337              256   0.1               64                    

(train_mnist pid=23954) WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
(train_mnist pid=23954) I0000 00:00:1733409840.272265   24056 service.cc:146] XLA service 0x78d5a8004820 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
(train_mnist pid=23954) I0000 00:00:1733409840.272309   24056 service.cc:154]   StreamExecutor device (0): NVIDIA L4, Compute Capability 8.9
(train_mnist pid=23954) I0000 00:00:1733409847.177319   24056 device_compiler.h:188] Compiled cluster using XLA!  This line is logged at most once for the lifetime of the process.


Trial status: 23 TERMINATED | 2 RUNNING | 2 PENDING
Current time: 2024-12-05 14:44:26. Total running time: 17min 32s
Logical resource usage: 2.0/12 CPUs, 1.0/1 GPUs (0.0/1.0 accelerator_type:L4)
Current best trial: f80bd_00007 with mean_accuracy=0.9981333613395691 and params={'conv_filters': 256, 'lr': 0.001, 'dropout': 0.00844249100058081, 'batch_size': 128}
+---------------------------------------------------------------------------------------------------------------------------------+
| Trial name                status         dropout     conv_filters      lr     batch_size        acc     iter     total time (s) |
+---------------------------------------------------------------------------------------------------------------------------------+
| train_mnist_f80bd_00023   RUNNING      0.615394               128   0.1              256                                        |
| train_mnist_f80bd_00024   RUNNING      0.0512337              256   0.1               64                    

(pid=25087) 2024-12-05 14:44:55.772760: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:485] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
(pid=25087) 2024-12-05 14:44:55.795537: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:8454] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
(pid=25087) 2024-12-05 14:44:55.802324: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1452] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered



Trial status: 24 TERMINATED | 1 RUNNING | 2 PENDING
Current time: 2024-12-05 14:44:56. Total running time: 18min 2s
Logical resource usage: 2.0/12 CPUs, 1.0/1 GPUs (0.0/1.0 accelerator_type:L4)
Current best trial: f80bd_00007 with mean_accuracy=0.9981333613395691 and params={'conv_filters': 256, 'lr': 0.001, 'dropout': 0.00844249100058081, 'batch_size': 128}
+---------------------------------------------------------------------------------------------------------------------------------+
| Trial name                status         dropout     conv_filters      lr     batch_size        acc     iter     total time (s) |
+---------------------------------------------------------------------------------------------------------------------------------+
| train_mnist_f80bd_00024   RUNNING      0.0512337              256   0.1               64                                        |
| train_mnist_f80bd_00000   TERMINATED   0.0800099               64   0.001             64   0.997583        1

(pid=25087) 2024-12-05 14:44:57.171567: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT



Trial train_mnist_f80bd_00025 started with configuration:
+-------------------------------------------------+
| Trial train_mnist_f80bd_00025 config            |
+-------------------------------------------------+
| batch_size                                  128 |
| conv_filters                                256 |
| dropout                                  0.4081 |
| lr                                          0.1 |
+-------------------------------------------------+


(train_mnist pid=25087) 2024-12-05 14:44:59.157203: W tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:47] Overriding orig_value setting because the TF_FORCE_GPU_ALLOW_GROWTH environment variable is set. Original config value was 0.
(train_mnist pid=25087) WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
(train_mnist pid=25087) I0000 00:00:1733409902.107310   25218 service.cc:146] XLA service 0x7ad4a4004f30 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
(train_mnist pid=25087) I0000 00:00:1733409902.107364   25218 service.cc:154]   StreamExecutor device (0): NVIDIA L4, Compute Capability 8.9
(train_mnist pid=25087) I0000 00:00:1733409913.116038   25218 device_compiler.h:188] Compiled cluster using XLA!  This line is logged at most once for the lifetime of the process.



Trial status: 24 TERMINATED | 2 RUNNING | 1 PENDING
Current time: 2024-12-05 14:45:26. Total running time: 18min 32s
Logical resource usage: 2.0/12 CPUs, 1.0/1 GPUs (0.0/1.0 accelerator_type:L4)
Current best trial: f80bd_00007 with mean_accuracy=0.9981333613395691 and params={'conv_filters': 256, 'lr': 0.001, 'dropout': 0.00844249100058081, 'batch_size': 128}
+---------------------------------------------------------------------------------------------------------------------------------+
| Trial name                status         dropout     conv_filters      lr     batch_size        acc     iter     total time (s) |
+---------------------------------------------------------------------------------------------------------------------------------+
| train_mnist_f80bd_00024   RUNNING      0.0512337              256   0.1               64                                        |
| train_mnist_f80bd_00025   RUNNING      0.408096               256   0.1              128                   

(pid=26433) 2024-12-05 14:46:50.627388: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:485] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
(pid=26433) 2024-12-05 14:46:50.649995: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:8454] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
(pid=26433) 2024-12-05 14:46:50.656529: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1452] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
(pid=26433) 2024-12-05 14:46:51.905682: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT



Trial train_mnist_f80bd_00026 started with configuration:
+--------------------------------------------------+
| Trial train_mnist_f80bd_00026 config             |
+--------------------------------------------------+
| batch_size                                   256 |
| conv_filters                                 256 |
| dropout                                  0.87814 |
| lr                                           0.1 |
+--------------------------------------------------+


(train_mnist pid=26433) 2024-12-05 14:46:53.781238: W tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:47] Overriding orig_value setting because the TF_FORCE_GPU_ALLOW_GROWTH environment variable is set. Original config value was 0.
(train_mnist pid=26433) WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
(train_mnist pid=26433) I0000 00:00:1733410016.501086   26532 service.cc:146] XLA service 0x7bcbd00041a0 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
(train_mnist pid=26433) I0000 00:00:1733410016.501132   26532 service.cc:154]   StreamExecutor device (0): NVIDIA L4, Compute Capability 8.9



Trial status: 25 TERMINATED | 2 RUNNING
Current time: 2024-12-05 14:46:57. Total running time: 20min 2s
Logical resource usage: 2.0/12 CPUs, 1.0/1 GPUs (0.0/1.0 accelerator_type:L4)
Current best trial: f80bd_00007 with mean_accuracy=0.9981333613395691 and params={'conv_filters': 256, 'lr': 0.001, 'dropout': 0.00844249100058081, 'batch_size': 128}
+---------------------------------------------------------------------------------------------------------------------------------+
| Trial name                status         dropout     conv_filters      lr     batch_size        acc     iter     total time (s) |
+---------------------------------------------------------------------------------------------------------------------------------+
| train_mnist_f80bd_00025   RUNNING      0.408096               256   0.1              128                                        |
| train_mnist_f80bd_00026   RUNNING      0.878145               256   0.1              256                                

(train_mnist pid=26433) I0000 00:00:1733410030.474018   26532 device_compiler.h:188] Compiled cluster using XLA!  This line is logged at most once for the lifetime of the process.


Trial status: 25 TERMINATED | 2 RUNNING
Current time: 2024-12-05 14:47:27. Total running time: 20min 32s
Logical resource usage: 2.0/12 CPUs, 1.0/1 GPUs (0.0/1.0 accelerator_type:L4)
Current best trial: f80bd_00007 with mean_accuracy=0.9981333613395691 and params={'conv_filters': 256, 'lr': 0.001, 'dropout': 0.00844249100058081, 'batch_size': 128}
+---------------------------------------------------------------------------------------------------------------------------------+
| Trial name                status         dropout     conv_filters      lr     batch_size        acc     iter     total time (s) |
+---------------------------------------------------------------------------------------------------------------------------------+
| train_mnist_f80bd_00025   RUNNING      0.408096               256   0.1              128                                        |
| train_mnist_f80bd_00026   RUNNING      0.878145               256   0.1              256                                

2024-12-05 14:48:42,236	INFO tune.py:1009 -- Wrote the latest version of all result files and experiment state to '/root/ray_results/train_mnist_2024-12-05_14-26-51' in 0.0086s.



Trial train_mnist_f80bd_00026 finished iteration 1 at 2024-12-05 14:48:42. Total running time: 21min 47s
+--------------------------------------------------+
| Trial train_mnist_f80bd_00026 result             |
+--------------------------------------------------+
| checkpoint_dir_name                              |
| time_this_iter_s                         109.028 |
| time_total_s                             109.028 |
| training_iteration                             1 |
| mean_accuracy                            0.10482 |
+--------------------------------------------------+

Trial train_mnist_f80bd_00026 completed after 1 iterations at 2024-12-05 14:48:42. Total running time: 21min 47s

Trial status: 27 TERMINATED
Current time: 2024-12-05 14:48:42. Total running time: 21min 47s
Logical resource usage: 1.0/12 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:L4)
Current best trial: f80bd_00007 with mean_accuracy=0.9981333613395691 and params={'conv_filters': 256, 'lr': 0.001, 'dropout': 0.00

In [ ]:
print("Best hyperparameters found were: ", analysis.best_config)
best_trial = analysis.best_trial    # 最佳试验
best_accuracy = best_trial.last_result["mean_accuracy"]
print(f"Best accuracy: {best_accuracy:.4f}")
time_taken = end_time - start_time
print(f"Time taken: {time_taken:.2f} seconds")

Best hyperparameters found were:  {'conv_filters': 256, 'lr': 0.001, 'dropout': 0.00844249100058081, 'batch_size': 128}
Best accuracy: 0.9981
Time taken: 1310.90 seconds


#### hyperband


In [ ]:
from ray.tune.schedulers import HyperBandScheduler
hyperband_scheduler = HyperBandScheduler(
    time_attr='training_iteration',
    metric='mean_accuracy',
    mode='max',
    max_t=10,
    reduction_factor=3)

In [ ]:
start_time = time.time()

analysis = tune.run(
        train_mnist,
        name="exp",
        resources_per_trial={
            "gpu": 1,
            "cpu": 4
        },
        config={
            "conv_filters": tune.randint(64,256),

            "batch_size": tune.grid_search([64, 128, 256]),
            "dropout": tune.uniform(0, 1),
            "lr": tune.uniform(0.001, 0.1)
        },
        scheduler=hyperband_scheduler,
        )
end_time = time.time()

+--------------------------------------------------------+
| Configuration for experiment     exp                   |
+--------------------------------------------------------+
| Search algorithm                 BasicVariantGenerator |
| Scheduler                        HyperBandScheduler    |
| Number of trials                 3                     |
+--------------------------------------------------------+

View detailed results here: /root/ray_results/exp
To visualize your results with TensorBoard, run: `tensorboard --logdir /tmp/ray/session_2024-12-05_14-26-48_632070_1199/artifacts/2024-12-05_14-49-31/exp/driver_artifacts`

Trial status: 3 PENDING
Current time: 2024-12-05 14:49:31. Total running time: 0s
Logical resource usage: 4.0/12 CPUs, 1.0/1 GPUs (0.0/1.0 accelerator_type:L4)
+---------------------------------------------------------------------------------------------+
| Trial name                status       conv_filters     dropout           lr     batch_size |
+----------

(pid=27967) 2024-12-05 14:49:32.987114: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:485] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
(pid=27967) 2024-12-05 14:49:33.009166: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:8454] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
(pid=27967) 2024-12-05 14:49:33.016040: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1452] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
(pid=27967) 2024-12-05 14:49:34.194034: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT



Trial train_mnist_228ce_00000 started with configuration:
+--------------------------------------------------+
| Trial train_mnist_228ce_00000 config             |
+--------------------------------------------------+
| batch_size                                    64 |
| conv_filters                                 167 |
| dropout                                  0.38638 |
| lr                                          0.05 |
+--------------------------------------------------+


(train_mnist pid=27967) 2024-12-05 14:49:36.004460: W tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:47] Overriding orig_value setting because the TF_FORCE_GPU_ALLOW_GROWTH environment variable is set. Original config value was 0.
(train_mnist pid=27967) WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
(train_mnist pid=27967) I0000 00:00:1733410178.584228   28083 service.cc:146] XLA service 0x7cb6e4005830 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
(train_mnist pid=27967) I0000 00:00:1733410178.584276   28083 service.cc:154]   StreamExecutor device (0): NVIDIA L4, Compute Capability 8.9
(train_mnist pid=27967) I0000 00:00:1733410184.043662   28083 device_compiler.h:188] Compiled cluster using XLA!  This line is logged at most once for the lifetime of the process.



Trial status: 1 RUNNING | 2 PENDING
Current time: 2024-12-05 14:50:01. Total running time: 30s
Logical resource usage: 4.0/12 CPUs, 1.0/1 GPUs (0.0/1.0 accelerator_type:L4)
+---------------------------------------------------------------------------------------------+
| Trial name                status       conv_filters     dropout           lr     batch_size |
+---------------------------------------------------------------------------------------------+
| train_mnist_228ce_00000   RUNNING               167    0.386379   0.0500024              64 |
| train_mnist_228ce_00001   PENDING               193    0.802119   0.0457266             128 |
| train_mnist_228ce_00002   PENDING               164    0.511372   0.00516603            256 |
+---------------------------------------------------------------------------------------------+
Trial status: 1 RUNNING | 2 PENDING
Current time: 2024-12-05 14:50:31. Total running time: 1min 0s
Logical resource usage: 4.0/12 CPUs, 1.0/1 GPUs (0.0/1.

(pid=28959) 2024-12-05 14:50:44.573305: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:485] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
(pid=28959) 2024-12-05 14:50:44.594768: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:8454] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
(pid=28959) 2024-12-05 14:50:44.601212: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1452] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
(pid=28959) 2024-12-05 14:50:45.777244: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT



Trial train_mnist_228ce_00001 started with configuration:
+--------------------------------------------------+
| Trial train_mnist_228ce_00001 config             |
+--------------------------------------------------+
| batch_size                                   128 |
| conv_filters                                 193 |
| dropout                                  0.80212 |
| lr                                       0.04573 |
+--------------------------------------------------+


(train_mnist pid=28959) 2024-12-05 14:50:47.566382: W tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:47] Overriding orig_value setting because the TF_FORCE_GPU_ALLOW_GROWTH environment variable is set. Original config value was 0.
(train_mnist pid=28959) WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
(train_mnist pid=28959) I0000 00:00:1733410250.208301   29070 service.cc:146] XLA service 0x7a9098006180 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
(train_mnist pid=28959) I0000 00:00:1733410250.208349   29070 service.cc:154]   StreamExecutor device (0): NVIDIA L4, Compute Capability 8.9
(train_mnist pid=28959) I0000 00:00:1733410257.373853   29070 device_compiler.h:188] Compiled cluster using XLA!  This line is logged at most once for the lifetime of the process.



Trial status: 1 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2024-12-05 14:51:01. Total running time: 1min 30s
Logical resource usage: 4.0/12 CPUs, 1.0/1 GPUs (0.0/1.0 accelerator_type:L4)
+--------------------------------------------------------------------------------------------------------------------------------------+
| Trial name                status         conv_filters     dropout           lr     batch_size        acc     iter     total time (s) |
+--------------------------------------------------------------------------------------------------------------------------------------+
| train_mnist_228ce_00001   RUNNING                 193    0.802119   0.0457266             128                                        |
| train_mnist_228ce_00000   TERMINATED              167    0.386379   0.0500024              64   0.103067        1             66.898 |
| train_mnist_228ce_00002   PENDING                 164    0.511372   0.00516603            256                          

(pid=30018) 2024-12-05 14:52:08.604617: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:485] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
(pid=30018) 2024-12-05 14:52:08.626509: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:8454] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
(pid=30018) 2024-12-05 14:52:08.633078: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1452] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
(pid=30018) 2024-12-05 14:52:09.810186: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT



Trial train_mnist_228ce_00002 started with configuration:
+--------------------------------------------------+
| Trial train_mnist_228ce_00002 config             |
+--------------------------------------------------+
| batch_size                                   256 |
| conv_filters                                 164 |
| dropout                                  0.51137 |
| lr                                       0.00517 |
+--------------------------------------------------+


(train_mnist pid=30018) 2024-12-05 14:52:11.636987: W tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:47] Overriding orig_value setting because the TF_FORCE_GPU_ALLOW_GROWTH environment variable is set. Original config value was 0.
(train_mnist pid=30018) WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
(train_mnist pid=30018) I0000 00:00:1733410334.200745   30124 service.cc:146] XLA service 0x7b06b8004b60 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
(train_mnist pid=30018) I0000 00:00:1733410334.200796   30124 service.cc:154]   StreamExecutor device (0): NVIDIA L4, Compute Capability 8.9
(train_mnist pid=30018) I0000 00:00:1733410341.726123   30124 device_compiler.h:188] Compiled cluster using XLA!  This line is logged at most once for the lifetime of the process.



Trial status: 2 TERMINATED | 1 RUNNING
Current time: 2024-12-05 14:52:31. Total running time: 3min 0s
Logical resource usage: 4.0/12 CPUs, 1.0/1 GPUs (0.0/1.0 accelerator_type:L4)
+--------------------------------------------------------------------------------------------------------------------------------------+
| Trial name                status         conv_filters     dropout           lr     batch_size        acc     iter     total time (s) |
+--------------------------------------------------------------------------------------------------------------------------------------+
| train_mnist_228ce_00002   RUNNING                 164    0.511372   0.00516603            256                                        |
| train_mnist_228ce_00000   TERMINATED              167    0.386379   0.0500024              64   0.103067        1            66.898  |
| train_mnist_228ce_00001   TERMINATED              193    0.802119   0.0457266             128   0.105317        1            79.1913

2024-12-05 14:53:16,003	INFO tune.py:1009 -- Wrote the latest version of all result files and experiment state to '/root/ray_results/exp' in 0.0041s.



Trial train_mnist_228ce_00002 finished iteration 1 at 2024-12-05 14:53:15. Total running time: 3min 44s
+--------------------------------------------------+
| Trial train_mnist_228ce_00002 result             |
+--------------------------------------------------+
| checkpoint_dir_name                              |
| time_this_iter_s                         64.9514 |
| time_total_s                             64.9514 |
| training_iteration                             1 |
| mean_accuracy                            0.99435 |
+--------------------------------------------------+

Trial train_mnist_228ce_00002 completed after 1 iterations at 2024-12-05 14:53:15. Total running time: 3min 44s

Trial status: 3 TERMINATED
Current time: 2024-12-05 14:53:16. Total running time: 3min 44s
Logical resource usage: 4.0/12 CPUs, 1.0/1 GPUs (0.0/1.0 accelerator_type:L4)
+--------------------------------------------------------------------------------------------------------------------------------------

In [ ]:
best_trial = analysis.get_best_trial("mean_accuracy", "max", "last")
best_accuracy = best_trial.metric_analysis["mean_accuracy"]["last"]
best_trial_config = best_trial.config
print(best_trial_config)
print(best_accuracy)
time_taken = end_time - start_time
print(f"Time taken: {time_taken:.2f} seconds")

{'conv_filters': 164, 'batch_size': 256, 'dropout': 0.5113715690967947, 'lr': 0.005166029382817264}
0.994350016117096
Time taken: 224.82 seconds


### Bayesian


In [ ]:
import time
from ray import train, tune
import torch
import torch.nn as nn
import torch.optim as optim
from torchvision import datasets, transforms
from torch.utils.data import DataLoader
# Define LeNet model
class LeNet(nn.Module):
    def __init__(self, num_filters, dropout):
        super(LeNet, self).__init__()
        self.conv1 = nn.Conv2d(1, num_filters, kernel_size=5)
        self.conv2 = nn.Conv2d(num_filters, 2 * num_filters, kernel_size=5)
        self.fc1 = nn.Linear(2 * num_filters * 4 * 4, 120)
        self.fc2 = nn.Linear(120, 84)
        self.fc3 = nn.Linear(84, 10)
        self.dropout = nn.Dropout(dropout)

    def forward(self, x):
        x = torch.relu(self.conv1(x))
        x = torch.max_pool2d(x, 2)
        x = torch.relu(self.conv2(x))
        x = torch.max_pool2d(x, 2)
        x = x.view(x.size(0), -1)
        x = torch.relu(self.fc1(x))
        x = self.dropout(torch.relu(self.fc2(x)))
        x = self.fc3(x)
        return x


In [ ]:
!pip show ray
!pip show bayesian-optimization


Name: ray
Version: 2.40.0
Summary: Ray provides a simple, universal API for building distributed applications.
Home-page: https://github.com/ray-project/ray
Author: Ray Team
Author-email: ray-dev@googlegroups.com
License: Apache 2.0
Location: /usr/local/lib/python3.10/dist-packages
Requires: aiosignal, click, filelock, frozenlist, jsonschema, msgpack, packaging, protobuf, pyyaml, requests
Required-by: 


In [ ]:
!pip uninstall bayesian-optimization -y


In [ ]:
!pip install bayesian-optimization==1.4.2

In [ ]:
!pip show bayesian-optimization


Name: bayesian-optimization
Version: 1.4.2
Summary: Bayesian Optimization package
Home-page: https://github.com/fmfn/BayesianOptimization
Author: Fernando Nogueira
Author-email: fmfnogueira@gmail.com
License: 
Location: /usr/local/lib/python3.10/dist-packages
Requires: colorama, numpy, scikit-learn, scipy
Required-by: 


In [ ]:

from ray.air import session

def train_mnist_bayesian(config):
    batch_size_mapping = [64, 128, 256]
    batch_size = batch_size_mapping[int(config["batch_size_idx"])]  # Convert index to actual batch size

    transform = transforms.Compose([transforms.ToTensor(), transforms.Normalize((0.5,), (0.5,))])
    train_dataset = datasets.MNIST(root="./data", train=True, download=True, transform=transform)
    val_dataset = datasets.MNIST(root="./data", train=False, download=True, transform=transform)

    train_loader = torch.utils.data.DataLoader(
        train_dataset, batch_size=batch_size, shuffle=True
    )
    val_loader = torch.utils.data.DataLoader(
        val_dataset, batch_size=batch_size, shuffle=False
    )

    device = "cuda" if torch.cuda.is_available() else "cpu"
    model = LeNet(int(config["num_filters"]), config["dropout"]).to(device)
    criterion = nn.CrossEntropyLoss()
    optimizer = optim.Adam(model.parameters(), lr=config["lr"])

    start_time = time.time()

    for epoch in range(12):
        model.train()
        for data, target in train_loader:
            data, target = data.to(device), target.to(device)
            optimizer.zero_grad()
            output = model(data)
            loss = criterion(output, target)
            loss.backward()
            optimizer.step()

    model.eval()
    correct = 0
    total = 0
    with torch.no_grad():
        for data, target in val_loader:
            data, target = data.to(device), target.to(device)
            output = model(data)
            _, predicted = torch.max(output, 1)
            total += target.size(0)
            correct += (predicted == target).sum().item()

    accuracy = correct / total

    total_time = time.time() - start_time
    session.report({"accuracy": accuracy, "time_total_s": total_time})
    print(f"Accuracy: {accuracy:.4f},Time: {total_time:.4f}")


In [ ]:
from ray.tune.search.bayesopt import BayesOptSearch

search_space = {
    "num_filters": tune.uniform(64, 256),
    "lr": tune.loguniform(0.001, 0.1),
    "batch_size_idx": tune.uniform(0, 2),  # Index for batch size
    "dropout": tune.uniform(0.0, 1.0)
}

search_alg = BayesOptSearch(metric="accuracy", mode="max")
start_time = time.time()
analysis = tune.run(
    train_mnist_bayesian,
    config=search_space,
    search_alg=search_alg,
    resources_per_trial={"cpu": 1, "gpu": 0.5},
    metric="accuracy",
    mode="max"
)
end_time = time.time()


best_config = analysis.get_best_config(metric="accuracy", mode="max")
batch_size_mapping = [64, 128, 256]
best_config["batch_size"] = batch_size_mapping[int(best_config.pop("batch_size_idx"))]

best_accuracy = analysis.best_result["accuracy"]
# best_time = analysis.best_result["time_total_s"]
time_taken = end_time - start_time





2024-12-05 15:11:46,271	WARNING bayesopt_search.py:431 -- BayesOpt does not support specific sampling methods. The LogUniform sampler will be dropped.


+-----------------------------------------------------------------------------+
| Configuration for experiment     train_mnist_bayesian_2024-12-05_15-11-46   |
+-----------------------------------------------------------------------------+
| Search algorithm                 SearchGenerator                            |
| Scheduler                        FIFOScheduler                              |
| Number of trials                 1                                          |
+-----------------------------------------------------------------------------+

View detailed results here: /root/ray_results/train_mnist_bayesian_2024-12-05_15-11-46
To visualize your results with TensorBoard, run: `tensorboard --logdir /tmp/ray/session_2024-12-05_15-02-24_292439_278/artifacts/2024-12-05_15-11-46/train_mnist_bayesian_2024-12-05_15-11-46/driver_artifacts`

Trial status: 1 PENDING
Current time: 2024-12-05 15:11:46. Total running time: 0s
Logical resource usage: 1.0/12 CPUs, 0.5/1 GPUs (0.0/1.0 acce

  0%|          | 0.00/9.91M [00:00<?, ?B/s]
  0%|          | 32.8k/9.91M [00:00<01:05, 151kB/s]
  1%|          | 65.5k/9.91M [00:00<01:05, 150kB/s]
  1%|▏         | 131k/9.91M [00:00<00:44, 219kB/s] 
  3%|▎         | 262k/9.91M [00:00<00:26, 369kB/s]
  5%|▌         | 524k/9.91M [00:01<00:14, 668kB/s]
 11%|█         | 1.05M/9.91M [00:01<00:07, 1.26MB/s]
 21%|██        | 2.10M/9.91M [00:01<00:03, 2.41MB/s]
 42%|████▏     | 4.19M/9.91M [00:01<00:01, 4.70MB/s]


(train_mnist_bayesian pid=4628) Extracting ./data/MNIST/raw/train-images-idx3-ubyte.gz to ./data/MNIST/raw


100%|██████████| 9.91M/9.91M [00:01<00:00, 5.02MB/s]


(train_mnist_bayesian pid=4628) 
(train_mnist_bayesian pid=4628) Downloading http://yann.lecun.com/exdb/mnist/train-labels-idx1-ubyte.gz
(train_mnist_bayesian pid=4628) Failed to download (trying next):
(train_mnist_bayesian pid=4628) HTTP Error 403: Forbidden
(train_mnist_bayesian pid=4628) 
(train_mnist_bayesian pid=4628) Downloading https://ossci-datasets.s3.amazonaws.com/mnist/train-labels-idx1-ubyte.gz
(train_mnist_bayesian pid=4628) Downloading https://ossci-datasets.s3.amazonaws.com/mnist/train-labels-idx1-ubyte.gz to ./data/MNIST/raw/train-labels-idx1-ubyte.gz


  0%|          | 0.00/28.9k [00:00<?, ?B/s]


(train_mnist_bayesian pid=4628) Extracting ./data/MNIST/raw/train-labels-idx1-ubyte.gz to ./data/MNIST/raw
(train_mnist_bayesian pid=4628) 
(train_mnist_bayesian pid=4628) Downloading http://yann.lecun.com/exdb/mnist/t10k-images-idx3-ubyte.gz


100%|██████████| 28.9k/28.9k [00:00<00:00, 65.1kB/s]


(train_mnist_bayesian pid=4628) Failed to download (trying next):
(train_mnist_bayesian pid=4628) HTTP Error 403: Forbidden
(train_mnist_bayesian pid=4628) 
(train_mnist_bayesian pid=4628) Downloading https://ossci-datasets.s3.amazonaws.com/mnist/t10k-images-idx3-ubyte.gz
(train_mnist_bayesian pid=4628) Downloading https://ossci-datasets.s3.amazonaws.com/mnist/t10k-images-idx3-ubyte.gz to ./data/MNIST/raw/t10k-images-idx3-ubyte.gz


  0%|          | 0.00/1.65M [00:00<?, ?B/s]
  2%|▏         | 32.8k/1.65M [00:00<00:32, 49.9kB/s]
  4%|▍         | 65.5k/1.65M [00:01<00:31, 51.1kB/s]
  6%|▌         | 98.3k/1.65M [00:01<00:26, 58.4kB/s]
  8%|▊         | 131k/1.65M [00:02<00:23, 63.6kB/s] 
 10%|▉         | 164k/1.65M [00:02<00:22, 67.2kB/s]
 12%|█▏        | 197k/1.65M [00:03<00:20, 70.0kB/s]
 14%|█▍        | 229k/1.65M [00:03<00:16, 84.2kB/s]
 16%|█▌        | 262k/1.65M [00:03<00:14, 97.7kB/s]
 18%|█▊        | 295k/1.65M [00:03<00:12, 110kB/s] 
 20%|█▉        | 328k/1.65M [00:03<00:10, 120kB/s]
 24%|██▍       | 393k/1.65M [00:04<00:07, 165kB/s]
 26%|██▌       | 426k/1.65M [00:04<00:07, 163kB/s]
 28%|██▊       | 459k/1.65M [00:04<00:07, 159kB/s]
 32%|███▏      | 524k/1.65M [00:04<00:05, 199kB/s]
 38%|███▊      | 623k/1.65M [00:05<00:03, 271kB/s]
 42%|████▏     | 688k/1.65M [00:05<00:03, 280kB/s]
 48%|████▊     | 786k/1.65M [00:05<00:02, 329kB/s]
 54%|█████▎    | 885k/1.65M [00:05<00:02, 365kB/s]
 60%|█████▉    | 983k/1.6

(train_mnist_bayesian pid=4628) Extracting ./data/MNIST/raw/t10k-images-idx3-ubyte.gz to ./data/MNIST/raw
(train_mnist_bayesian pid=4628) 
(train_mnist_bayesian pid=4628) Downloading http://yann.lecun.com/exdb/mnist/t10k-labels-idx1-ubyte.gz


100%|██████████| 1.65M/1.65M [00:06<00:00, 242kB/s]


(train_mnist_bayesian pid=4628) Failed to download (trying next):
(train_mnist_bayesian pid=4628) HTTP Error 403: Forbidden
(train_mnist_bayesian pid=4628) 
(train_mnist_bayesian pid=4628) Downloading https://ossci-datasets.s3.amazonaws.com/mnist/t10k-labels-idx1-ubyte.gz
(train_mnist_bayesian pid=4628) Downloading https://ossci-datasets.s3.amazonaws.com/mnist/t10k-labels-idx1-ubyte.gz to ./data/MNIST/raw/t10k-labels-idx1-ubyte.gz
(train_mnist_bayesian pid=4628) Extracting ./data/MNIST/raw/t10k-labels-idx1-ubyte.gz to ./data/MNIST/raw
(train_mnist_bayesian pid=4628) 


100%|██████████| 4.54k/4.54k [00:00<00:00, 14.1MB/s]



Trial status: 1 RUNNING
Current time: 2024-12-05 15:12:16. Total running time: 30s
Logical resource usage: 1.0/12 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:A100)
+-----------------------------------------------------------------------------------------------------+
| Trial name                      status       num_filters          lr     batch_size_idx     dropout |
+-----------------------------------------------------------------------------------------------------+
| train_mnist_bayesian_61e69b58   RUNNING          178.942   0.0734674            0.74908    0.950714 |
+-----------------------------------------------------------------------------------------------------+
Trial status: 1 RUNNING
Current time: 2024-12-05 15:12:46. Total running time: 1min 0s
Logical resource usage: 1.0/12 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:A100)
+-----------------------------------------------------------------------------------------------------+
| Trial name                      status     

2024-12-05 15:15:11,903	INFO tune.py:1009 -- Wrote the latest version of all result files and experiment state to '/root/ray_results/train_mnist_bayesian_2024-12-05_15-11-46' in 0.0039s.



Trial train_mnist_bayesian_61e69b58 finished iteration 1 at 2024-12-05 15:15:11. Total running time: 3min 25s
+--------------------------------------------------------+
| Trial train_mnist_bayesian_61e69b58 result             |
+--------------------------------------------------------+
| checkpoint_dir_name                                    |
| time_this_iter_s                               201.275 |
| time_total_s                                   201.275 |
| training_iteration                                   1 |
| accuracy                                        0.0892 |
+--------------------------------------------------------+

Trial train_mnist_bayesian_61e69b58 completed after 1 iterations at 2024-12-05 15:15:11. Total running time: 3min 25s

Trial status: 1 TERMINATED
Current time: 2024-12-05 15:15:11. Total running time: 3min 25s
Logical resource usage: 1.0/12 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:A100)
Current best trial: 61e69b58 with accuracy=0.0892 and params={'num_

In [ ]:
print("Best hyperparameters:", best_config)
print(f"Best validation accuracy: {best_accuracy:.4f}")
print(f"Time taken: {time_taken:.2f} seconds")

Best hyperparameters: {'num_filters': 178.94242896583103, 'lr': 0.07346740023932911, 'dropout': 0.9507143064099162, 'batch_size': 64}
Best validation accuracy: 0.0892
Time taken: 205.67 seconds


## Part 3.

For these three methods, Grid search takes the longest time to find the best model with accuracy is 0.9981. While for the other two, although they are faster, their accuracies are incredible low. For Bayesian, the hyperparameter's range is too big thus it hard to perform well. For Hyperband, it relys on early stopping which may stop too early. Thus Grid Search produced the best model with the highest validation accuracy but at the cost of significantly higher computation time. Both Bayesian Optimization and Hyperband were faster but failed to identify the best hyperparameter configurations if we don't set the stop point, leading to very poor model performance.

# Problem 3

### Setup

- **Learner 1 (L1)** computes gradients:
  - \( g[L_1, 1] \) at \( t = 1 \)
  - \( g[L_1, 2] \) at \( t = 2 \)
  - \( g[L_1, 3] \) at \( t = 3 \)
  - \( g[L_1, 4] \) at \( t = 4 \)

- **Learner 2 (L2)** computes gradients:
  - \( g[L_2, 1] \) at \( t = 2.5 \)
  - \( g[L_2, 2] \) at \( t = 5 \)

---

### Step-by-Step Staleness Calculation

1. **\( g[L_1, 1] \):**
   - Computed at \( t = 1 \).
   - No updates have occurred before this gradient is used.
   - **Staleness = 0**

2. **\( g[L_1, 2] \):**
   - Computed at \( t = 2 \).
   - No updates have occurred before this gradient is used.
   - **Staleness = 0**

3. **\( g[L_2, 1] \):**
   - Computed at \( t = 2.5 \).
   - By this time, \( g[L_1, 1] \) and \( g[L_1, 2] \) have been used to update weights.
   - **Staleness = 2**

4. **\( g[L_1, 3] \):**
   - Computed at \( t = 3 \).
   - By this time, \( g[L_2, 1] \) has been used to update weights.
   - **Staleness = 1**

5. **\( g[L_1, 4] \):**
   - Computed at \( t = 4 \).
   - By this time, \( g[L_1, 3] \) has been used to update weights.
   - **Staleness = 0**

6. **\( g[L_2, 2] \):**
   - Computed at \( t = 5 \).
   - By this time, \( g[L_1, 4] \) and \( g[L_1, 3] \) have been used to update weights.
   - **Staleness = 3**

* $L_1$ : $g[L_1,1]$ at second 1, staleness = 0
* $L_1$ : $g[L_1,2]$ at second 2, staleness = 0
* $L_1$ : $g[L_1,3]$ at second 3, staleness = 1
* $L_1$ : $g[L_1,4]$ at second 4, staleness = 0
* $L_2$ : $g[L_2,1]$ at second 2.5, staleness = 2
* $L_2$ : $g[L_2,2]$ at second 5, staleness = 2


# Problem 4

## Part 1.

In [ ]:
!git clone https://github.com/kuangliu/pytorch-cifar.git
!cd pytorch-cifar


Cloning into 'pytorch-cifar'...
remote: Enumerating objects: 382, done.
remote: Total 382 (delta 0), reused 0 (delta 0), pack-reused 382 (from 1)
Receiving objects: 100% (382/382), 81.31 KiB | 2.39 MiB/s, done.
Resolving deltas: 100% (198/198), done.


In [ ]:
import os
print("Current Working Directory: ", os.getcwd())

Current Working Directory:  /content


In [ ]:
import sys

# 添加 pytorch-cifar 到 sys.path
sys.path.append('/content/pytorch-cifar')

# 现在尝试再次导入
from models.resnet import ResNet18

In [ ]:
import torch
import torch.nn as nn
from models.resnet import ResNet18
import torchvision
import torchvision.transforms as transforms
from torch.utils.data import DataLoader
import torch.optim as optim

In [ ]:

# Assuming you are using the ResNet18 from the cloned repo
model = ResNet18()



In [ ]:
transform = transforms.Compose([
    transforms.RandomCrop(32, padding=4),
    transforms.RandomHorizontalFlip(p=0.5),
    transforms.ToTensor(),
    transforms.Normalize((0.4914, 0.4822, 0.4465), (0.2023, 0.1994, 0.2010))
])

In [ ]:
trainset = torchvision.datasets.CIFAR10(root='./data', train=True, download=True, transform=transform)

100%|██████████| 170M/170M [00:01<00:00, 94.8MB/s]


Extracting ./data/cifar-10-python.tar.gz to ./data


In [ ]:
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
model = ResNet18().to(device)
optimizer = optim.SGD(model.parameters(), lr=0.1, momentum=0.9, weight_decay=5e-4)

In [ ]:
import torch
from torch.utils.data import DataLoader
import torch.nn as nn
import time

batch_size = 32
times = []

while True:
    try:

        trainloader = DataLoader(trainset, batch_size=batch_size, shuffle=True, num_workers=2)


        model.train()
        for data in trainloader:
            inputs, labels = data[0].to(device), data[1].to(device)
            optimizer.zero_grad()
            outputs = model(inputs)
            loss = nn.CrossEntropyLoss()(outputs, labels)
            loss.backward()
            optimizer.step()


        start_time = time.time()
        for data in trainloader:
            inputs, labels = data[0].to(device), data[1].to(device)
            optimizer.zero_grad()
            outputs = model(inputs)
            loss = nn.CrossEntropyLoss()(outputs, labels)
            loss.backward()
            optimizer.step()
        end_time = time.time()

        epoch_time = end_time - start_time
        times.append(epoch_time)
        print(f"Batch Size: {batch_size}, Time: {epoch_time:.2f} seconds")


        batch_size *= 4

    except RuntimeError as e:
        if "CUDA out of memory" in str(e):
            print(f"Batch size {batch_size} exceeds GPU memory capacity.")
            break
        else:
            raise



for size, t in zip([32 * (4 ** i) for i in range(len(times))], times):
    print(f"Batch Size: {size}, Time: {t:.2f} seconds")


Batch Size: 32, Time: 17.59 seconds
Batch Size: 128, Time: 10.73 seconds
Batch Size: 512, Time: 10.28 seconds
Batch Size: 2048, Time: 10.55 seconds
Batch Size: 8192, Time: 11.66 seconds
Batch size 32768 exceeds GPU memory capacity.
Batch Size: 32, Time: 17.59 seconds
Batch Size: 128, Time: 10.73 seconds
Batch Size: 512, Time: 10.28 seconds
Batch Size: 2048, Time: 10.55 seconds
Batch Size: 8192, Time: 11.66 seconds


## Part 2.

#### GPU - 4

In [ ]:
model = nn.DataParallel(model, device_ids=[0, 1, 2, 3])
model.to(device)

DataParallel(
  (module): ResNet(
    (conv1): Conv2d(3, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
    (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (layer1): Sequential(
      (0): BasicBlock(
        (conv1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
        (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
        (bn2): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (shortcut): Sequential()
      )
      (1): BasicBlock(
        (conv1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
        (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
       

In [ ]:

criterion = nn.CrossEntropyLoss()
import time
optimizer = optim.SGD(model.parameters(), lr=0.1, momentum=0.9, weight_decay=5e-4)

In [ ]:
batch_sizes = [32, 128, 512]
results = []

for batch_size in batch_sizes:
    trainloader = DataLoader(trainset, batch_size=batch_size * torch.cuda.device_count(), shuffle=True, num_workers=2)


    for _ in range(1):
        for inputs, labels in trainloader:
            inputs, labels = inputs.to(device), labels.to(device)
            optimizer.zero_grad()
            outputs = model(inputs)
            loss = criterion(outputs, labels)
            loss.backward()
            optimizer.step()


    start_time = time.time()
    for inputs, labels in trainloader:
        inputs, labels = inputs.to(device), labels.to(device)
        optimizer.zero_grad()
        outputs = model(inputs)
        loss = criterion(outputs, labels)
        loss.backward()
        optimizer.step()
    end_time = time.time()

    epoch_time = end_time - start_time
    results.append((batch_size, epoch_time))


for batch_size, timing in results:
    print(f"Batch Size {batch_size}, Time: {timing:.2f} sec")


Batch Size 32, Time: 16.71 sec
Batch Size 128, Time: 9.30 sec
Batch Size 512, Time: 9.26 sec


#### GPU -2

In [ ]:
# GPU 2

model = nn.DataParallel(model, device_ids=[0, 1])
model.to(device)
criterion = nn.CrossEntropyLoss()
import time
optimizer = optim.SGD(model.parameters(), lr=0.1, momentum=0.9, weight_decay=5e-4)

In [ ]:
batch_sizes = [32, 128, 512]
results = []

for batch_size in batch_sizes:
    trainloader = DataLoader(trainset, batch_size=batch_size * torch.cuda.device_count(), shuffle=True, num_workers=2)


    for _ in range(1):
        for inputs, labels in trainloader:
            inputs, labels = inputs.to(device), labels.to(device)
            optimizer.zero_grad()
            outputs = model(inputs)
            loss = criterion(outputs, labels)
            loss.backward()
            optimizer.step()


    start_time = time.time()
    for inputs, labels in trainloader:
        inputs, labels = inputs.to(device), labels.to(device)
        optimizer.zero_grad()
        outputs = model(inputs)
        loss = criterion(outputs, labels)
        loss.backward()
        optimizer.step()
    end_time = time.time()

    epoch_time = end_time - start_time
    results.append((batch_size, epoch_time))


for batch_size, timing in results:
    print(f"Batch Size {batch_size}, Time: {timing:.2f} sec")


Batch Size 32, Time: 16.23 sec
Batch Size 128, Time: 9.32 sec
Batch Size 512, Time: 9.48 sec


| GPU Configuration | Batch Size per GPU | Time (sec) | Speedup |
|-------------------|--------------------|------------|---------|
| 1-GPU             | 32                 | 17.59      | 1       |
| 1-GPU             | 128                | 10.73      | 1       |
| 1-GPU             | 512                | 10.28      | 1       |
| 2-GPU             | 32                 | 16.23      | 1.22    |
| 2-GPU             | 128                | 9.32      | 1.15    |
| 2-GPU             | 512                | 9.48      | 1.08    |
| 4-GPU             | 32                 | 16.71      | 1.18    |
| 4-GPU             | 128                | 9.30       | 1.16    |
| 4-GPU             | 512                | 9.26       | 1.08    |


This is Strong-scaling. If we were to use weak scaling instead, where each additional GPU added comes with a proportionate increase in workload to keep the load per GPU consistent, the execution time is ideally meant to stay about the same instead of decreasing. Weak scaling might prove to be better in this scenarios.

## Part 3.

#### Batch Size: 32
- **Single GPU Time**: 17.59 seconds
- **2-GPU Total Time**: 16.23 seconds
- **4-GPU Total Time**: 16.71 seconds
- **Estimated Compute Time** (75% of Single GPU Time): `17.59 * 0.75 = 13.19` seconds
- **2-GPU Communication Time**: `16.23 - 13.19 = 3.04` seconds
- **4-GPU Communication Time**: `16.71 - 13.19 = 3.52` seconds

#### Batch Size: 128
- **Single GPU Time**: 10.76 seconds
- **2-GPU Total Time**: 9.32 seconds
- **4-GPU Total Time**: 9.30 seconds
- **Estimated Compute Time**: `10.73 * 0.75 = 8.05` seconds
- **2-GPU Communication Time**: `9.32 - 8.05 = 1.27` seconds
- **4-GPU Communication Time**: `9.30 - 8.05 = 1.25` seconds

#### Batch Size: 512
- **Single GPU Time**: 10.26 seconds
- **2-GPU Total Time**: 9.48 seconds
- **4-GPU Total Time**: 9.26 seconds
- **Estimated Compute Time**: `10.28 * 0.75 = 7.71` seconds
- **2-GPU Communication Time**: `9.48 - 7.71 = 1.77` seconds
- **4-GPU Communication Time**: `9.26 - 7.71 = 1.55` seconds

### Compiled Table (Complete Data)

| GPU Configuration | Batch Size | Compute(sec) | Comm(sec) |
|-------------------|------------|--------------|-----------|
| 2-GPU             | 32         | 13.19       | 3.04      |
| 4-GPU             | 32         | 13.19        | 3.52     |
| 2-GPU             | 128        | 8.05        | 1.27      |
| 4-GPU             | 128        | 8.05         | 1.25      |
| 2-GPU             | 512        | 7.71         | 1.77      |
| 4-GPU             | 512        | 7.71        | 1.55     |

## Part 4


In [ ]:
import torch
import torch.nn as nn
from torchvision.models import resnet18

# 定义 ResNet-18 模型
def get_model():
    model = resnet18()
    model.fc = nn.Linear(model.fc.in_features, 10)  # 调整最后一层以适配 CIFAR10 数据集
    return model

# 计算梯度大小（单位：GB）
def calculate_gradient_size(model):
    gradient_size = sum(p.numel() for p in model.parameters() if p.requires_grad)
    gradient_size_bytes = gradient_size * 4
    gradient_size_gb = gradient_size_bytes / (1024**3)
    return gradient_size_gb


def calculate_bandwidth_utilization(num_gpus, batch_sizes, communication_times):
    model = get_model()
    gradient_size_gb = calculate_gradient_size(model)
    results = []

    for batch_size, comm_time in zip(batch_sizes, communication_times):

        bandwidth_utilization = gradient_size_gb / comm_time
        results.append({
            'Batch Size per GPU': batch_size,
            'Communication Time (sec)': comm_time,
            'Bandwidth Utilization (GB/s)': bandwidth_utilization
        })
        print(f"Batch Size per GPU: {batch_size}, Communication Time: {comm_time:.4f}s, Bandwidth Utilization: {bandwidth_utilization:.4f} GB/s")

    return results

if __name__ == "__main__":

    communication_times_2gpu = [3.04, 1.27, 1.77]  # 2 GPUs
    communication_times_4gpu = [3.52, 1.25, 1.55]  # 4 GPUs


    batch_sizes = [32, 128, 512]

    print("\n--- Bandwidth Utilization for 2 GPUs ---")
    results_2gpu = calculate_bandwidth_utilization(2, batch_sizes, communication_times_2gpu)

    print("\n--- Bandwidth Utilization for 4 GPUs ---")
    results_4gpu = calculate_bandwidth_utilization(4, batch_sizes, communication_times_4gpu)



--- Bandwidth Utilization for 2 GPUs ---
Batch Size per GPU: 32, Communication Time: 3.0400s, Bandwidth Utilization: 0.0137 GB/s
Batch Size per GPU: 128, Communication Time: 1.2700s, Bandwidth Utilization: 0.0328 GB/s
Batch Size per GPU: 512, Communication Time: 1.7700s, Bandwidth Utilization: 0.0235 GB/s

--- Bandwidth Utilization for 4 GPUs ---
Batch Size per GPU: 32, Communication Time: 3.5200s, Bandwidth Utilization: 0.0118 GB/s
Batch Size per GPU: 128, Communication Time: 1.2500s, Bandwidth Utilization: 0.0333 GB/s
Batch Size per GPU: 512, Communication Time: 1.5500s, Bandwidth Utilization: 0.0269 GB/s




1.   $ T_{\text{allreduce}} = \left(2 \times (n-1) \times (L+\frac{m}{nb}) \right)$
2.   $ U = \frac{\frac{m}{n}}{b \times (L+\frac{m}{nb})}$
3. Table 3

| GPU Configuration | Batch Size | Bandwidth Utilization (GB/s) |
|-------------------|------------|------------------------------|
| 2-GPU             | 32         | 0.0137                       |
| 2-GPU             | 128        | 0.0328                        |
| 2-GPU             | 512        | 0.0235                      |
| 4-GPU             | 32         | 0.0118                    |
| 4-GPU             | 128        | 0.0333                    |
| 4-GPU             | 512        | 0.0269                      |

